--liquibase formatted sql
-- GENERATED by apps/his_frontend/scripts/export-mocks, do not edit

--changeset his-ref:001-vital-threshold context:reference
INSERT INTO vital_threshold (type, label, unit, low, high, critical_low, critical_high, min_value, max_value) VALUES
    ('systolic', 'Ciśnienie skurczowe', 'mmHg', 90, 140, 80, 180, 40, 260),
    ('diastolic', 'Ciśnienie rozkurczowe', 'mmHg', 60, 90, 50, 110, 20, 180),
    ('heartRate', 'Tętno', '/min', 50, 100, 40, 130, 20, 250),
    ('temperature', 'Temperatura', '°C', 36, 37.5, 35, 39.5, 30, 43),
    ('spo2', 'Saturacja SpO₂', '%', 94, 100, 90, 100, 50, 100),
    ('respiratoryRate', 'Częstość oddechów', '/min', 12, 20, 8, 25, 4, 60);
