import type { VitalThreshold, VitalType } from '../models';

export const VITAL_THRESHOLDS: Record<VitalType, VitalThreshold> = {
  systolic: {
    type: 'systolic',
    label: 'Ciśnienie skurczowe',
    unit: 'mmHg',
    low: 90,
    high: 140,
    criticalLow: 80,
    criticalHigh: 180,
    min: 40,
    max: 260,
  },
  diastolic: {
    type: 'diastolic',
    label: 'Ciśnienie rozkurczowe',
    unit: 'mmHg',
    low: 60,
    high: 90,
    criticalLow: 50,
    criticalHigh: 110,
    min: 20,
    max: 180,
  },
  heartRate: {
    type: 'heartRate',
    label: 'Tętno',
    unit: '/min',
    low: 50,
    high: 100,
    criticalLow: 40,
    criticalHigh: 130,
    min: 20,
    max: 250,
  },
  temperature: {
    type: 'temperature',
    label: 'Temperatura',
    unit: '°C',
    low: 36.0,
    high: 37.5,
    criticalLow: 35,
    criticalHigh: 39.5,
    min: 30,
    max: 43,
  },
  spo2: {
    type: 'spo2',
    label: 'Saturacja SpO₂',
    unit: '%',
    low: 94,
    high: 100,
    criticalLow: 90,
    criticalHigh: 100,
    min: 50,
    max: 100,
  },
  respiratoryRate: {
    type: 'respiratoryRate',
    label: 'Częstość oddechów',
    unit: '/min',
    low: 12,
    high: 20,
    criticalLow: 8,
    criticalHigh: 25,
    min: 4,
    max: 60,
  },
};
