--liquibase formatted sql
-- GENERATED by apps/his_frontend/scripts/export-mocks, do not edit

--changeset his-mock:001-ward context:mock
INSERT INTO ward (id, name, short_name, floor, beds) VALUES
    ('25c25490-5067-5aaa-bcf5-5dc23f56588b', 'Oddział Chorób Wewnętrznych', 'INT', '2', 30),
    ('36877e50-4f0b-5b6c-bc22-983228fe0d83', 'Kardiologia', 'KAR', '3', 24),
    ('b0225b77-deaa-5d03-b73e-931004b89234', 'Chirurgia Ogólna', 'CHG', '1', 26),
    ('7bb51afa-214b-501b-b216-7b78276e538b', 'Neurologia', 'NEU', '4', 20),
    ('1839f924-5e1b-5ceb-963f-f2ee1592947a', 'Szpitalny Oddział Ratunkowy', 'SOR', '0', 12),
    ('9062e817-70be-578e-b07e-136085e8e294', 'Poradnia Ogólna', 'AMB', '0', 0);

--changeset his-mock:001-staff-member context:mock
INSERT INTO staff_member (id, title, first_name, last_name, role, specialization, ward_id, phone, pwz, employee_id, email) VALUES
    ('16259545-f97c-531d-b9cd-6ba115379372', 'lek.', 'Anna', 'Nowak', 'doctor', 'Choroby wewnętrzne', '25c25490-5067-5aaa-bcf5-5dc23f56588b', '+48 601 100 001', '2001117', 'EMP-0001', NULL),
    ('6a2063f1-ade9-52c8-a1b0-f894c0093d46', 'dr n. med.', 'Piotr', 'Wiśniewski', 'doctor', 'Kardiologia', '36877e50-4f0b-5b6c-bc22-983228fe0d83', '+48 601 100 002', '2002234', 'EMP-0002', NULL),
    ('19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', 'lek.', 'Tomasz', 'Kamiński', 'doctor', 'Chirurgia ogólna', 'b0225b77-deaa-5d03-b73e-931004b89234', '+48 601 100 003', '2003351', 'EMP-0003', NULL),
    ('0ffcc103-5e1d-5346-aeba-8f9907cce3df', 'lek.', 'Marta', 'Lewandowska', 'doctor', 'Neurologia', '7bb51afa-214b-501b-b216-7b78276e538b', '+48 601 100 004', '2004468', 'EMP-0004', NULL),
    ('fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', 'lek.', 'Paweł', 'Zieliński', 'doctor', 'Medycyna ratunkowa', '1839f924-5e1b-5ceb-963f-f2ee1592947a', '+48 601 100 005', '2005585', 'EMP-0005', NULL),
    ('625e824c-3b63-51c2-9e56-78cbfd0ff9a5', 'mgr piel.', 'Katarzyna', 'Zielińska', 'nurse', NULL, '25c25490-5067-5aaa-bcf5-5dc23f56588b', '+48 601 100 006', '2006702', 'EMP-0006', NULL),
    ('f9dd7885-41c2-5cf0-a4ca-2a5b45474502', 'piel.', 'Magdalena', 'Wójcik', 'nurse', NULL, '36877e50-4f0b-5b6c-bc22-983228fe0d83', '+48 601 100 007', '2007819', 'EMP-0007', NULL),
    ('570c2cc4-eafe-5082-a1ca-e47097316d3a', 'piel.', 'Ewa', 'Lewandowska', 'nurse', 'Pielęgniarka oddziałowa', 'b0225b77-deaa-5d03-b73e-931004b89234', '+48 601 100 008', '2008936', 'EMP-0008', NULL),
    ('42fb062f-6dc8-574b-b1bd-fc33c5e4decb', 'piel.', 'Agnieszka', 'Kaczmarek', 'nurse', NULL, '7bb51afa-214b-501b-b216-7b78276e538b', '+48 601 100 009', '2010053', 'EMP-0009', NULL),
    ('fbda300f-3c9a-515b-9a3b-ad2b1a7d9775', 'piel.', 'Michał', 'Szymański', 'nurse', NULL, '1839f924-5e1b-5ceb-963f-f2ee1592947a', '+48 601 100 010', '2011170', 'EMP-0010', NULL);

--changeset his-mock:001-user-account context:mock
INSERT INTO user_account (id, staff_id, employee_id, password_hash, account_status) VALUES
    ('59a6f62c-938d-5b33-8396-f93dc07419db', '16259545-f97c-531d-b9cd-6ba115379372', 'EMP-0001', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('725ccadb-2270-5817-9248-72067893fc11', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', 'EMP-0002', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('98a0e617-3e58-5f49-94ea-70d75246a346', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', 'EMP-0003', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('fee83f15-abf9-58fd-be0d-86700710da7d', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', 'EMP-0004', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('87839476-a18c-53b4-95d8-535a41176a08', 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', 'EMP-0005', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('59c8fe48-d705-5a4f-b41a-e473d0301e40', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', 'EMP-0006', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('4ea9d6f5-ae33-5527-876e-c504b614419d', 'f9dd7885-41c2-5cf0-a4ca-2a5b45474502', 'EMP-0007', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('0173c03c-58f0-5d33-a471-4b1325d6f72b', '570c2cc4-eafe-5082-a1ca-e47097316d3a', 'EMP-0008', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('5bc3ebdb-0559-5e36-9c84-a946153ec224', '42fb062f-6dc8-574b-b1bd-fc33c5e4decb', 'EMP-0009', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active'),
    ('8cd3ecf4-93dd-51b1-8f04-54ae2b71a2ae', 'fbda300f-3c9a-515b-9a3b-ad2b1a7d9775', 'EMP-0010', '$2a$10$5oDBlRGwsrFsuDdeTl/EPOPDhCFr3VoyDb1Bi.4B4hn3fKXcGdmnC', 'active');
