--liquibase formatted sql
-- GENERATED by apps/his_frontend/scripts/export-mocks, do not edit

--changeset his-mock:005-clinical-note context:mock
INSERT INTO clinical_note (id, patient_id, encounter_id, author_id, category, title, content, created_at, updated_at) VALUES
    ('725473be-5cdf-53a2-b7f0-d9638383648b', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', '11b7050d-6f4c-546a-9bf7-da0f024b363e', '16259545-f97c-531d-b9cd-6ba115379372', 'admission', 'Przyjęcie do oddziału', 'Pacjent przyjęty z powodu duszności wysiłkowej i narastających obrzęków kończyn dolnych, utrzymujących się od 5 dni. W badaniu przedmiotowym: trzeszczenia u podstawy obu płuc, obrzęki podudzi. Rozpoczęto leczenie diuretyczne.', now() - interval '76 hours', now() - interval '76 hours'),
    ('76cdea00-f4be-5456-a363-01c35b8ace71', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', '11b7050d-6f4c-546a-9bf7-da0f024b363e', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', 'nursing', 'Obserwacja pielęgniarska', 'Pacjent w stanie ogólnym dobrym. Bilans płynów dodatni, kontynuacja leczenia moczopędnego. Masa ciała spadła o 1,2 kg w ciągu doby.', now() - interval '52 hours', now() - interval '52 hours'),
    ('814d9636-6b20-5c86-8d4c-48e6f8f21ea1', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', 'd4f638d6-9488-5d4e-b308-a85cbf76c064', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', 'consultation', 'Konsultacja kardiologiczna', 'Zalecono zwiększenie dawki furosemidu oraz kontrolę elektrolitów co 48h. Echo serca planowane w ciągu tygodnia.', now() - interval '52 hours', now() - interval '52 hours'),
    ('3abd19d9-3239-5fd6-95ce-37f7fdd77f5b', '7466c824-06b6-57f2-8bae-2f20f77d64b6', '2e790042-5ce2-543b-baee-416bf421230d', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', 'admission', 'Przyjęcie - podejrzenie ACS', 'Pacjentka zgłosiła się z bólem zamostkowym o charakterze uciskowym, promieniującym do lewej ręki, trwającym ok. 40 minut. W EKG uniesienie odcinka ST w odprowadzeniach II, III, aVF. Wykonano pilną koronarografię.', now() - interval '28 hours', now() - interval '28 hours'),
    ('7e613274-ccf4-5f16-b0c2-03b0e53329be', '7466c824-06b6-57f2-8bae-2f20f77d64b6', '12e1c4f3-99c3-537c-aa2e-1c91cd4ad81a', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', 'progress', 'Stan po koronarografii', 'Zabieg przebiegł bez powikłań. Implantowano stent do gałęzi okalającej. Pacjentka w stanie stabilnym, bóle wieńcowe ustąpiły.', now() - interval '19 hours', now() - interval '19 hours'),
    ('2dfde60d-69bb-5691-a3e2-fe2ce90852d7', 'a8500c41-1152-563d-b249-363417666099', 'b3c81116-d377-5ae3-a4a6-0807e9ff63d9', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', 'admission', 'Przyjęcie - udar niedokrwienny', 'Pacjentka przywieziona przez zespół ratownictwa medycznego z niedowładem połowiczym prawostronnym i zaburzeniami mowy, wywiad ok. 2h. Wykonano TK głowy, włączono leczenie trombolityczne.', now() - interval '124 hours', now() - interval '124 hours'),
    ('677ed6ba-7d72-53b5-95c4-e5e95ed7243d', 'a8500c41-1152-563d-b249-363417666099', 'f5ef2086-ef06-5ab2-96d2-2e4be9d9de54', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', 'consultation', 'Ocena rehabilitacyjna', 'Rozpoczęto wczesną rehabilitację ruchową. Siła mięśniowa kończyny górnej prawej 3/5, dolnej 4/5. Kontynuacja ćwiczeń.', now() - interval '100 hours', now() - interval '100 hours'),
    ('78eab1ac-7d6b-55f6-845e-2c1c06ea5f5d', 'dfb16109-f62b-5791-a571-a3652caa0ea7', '05ee0b41-7454-5a2d-a52b-8d1542df4f69', '16259545-f97c-531d-b9cd-6ba115379372', 'discharge', 'Wypis ze szpitala', 'Pacjent w stanie ogólnym dobrym, ustąpiły objawy zapalenia płuc. Zakończono antybiotykoterapię dożylną. Zalecono kontrolę w poradni POZ za 2 tygodnie.', now() - interval '244 hours', now() - interval '244 hours'),
    ('bf0e574c-0415-5112-89a0-f578b2235daf', '50c8f3fa-ea66-581a-9207-f9c4c7131d26', '74af2b98-d14c-5c03-8a89-86cf57e8c170', 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', 'admission', 'Przyjęcie na SOR - uraz wielonarządowy', 'Pacjent po wypadku komunikacyjnym, przywieziony przez zespół LPR. Triage czerwony. Wykonano TK całego ciała, stwierdzono uraz głowy i złamanie żeber.', now() - interval '6 hours', now() - interval '6 hours'),
    ('63fd5c1d-c5b7-517f-8e46-72f924b13d92', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', '3d21b7f3-1194-590f-81b4-132e899ef5f5', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', 'admission', 'Przyjęcie planowe', 'Pacjent przyjęty planowo celem przygotowania do cholecystektomii laparoskopowej z powodu objawowej kamicy żółciowej.', now() - interval '52 hours', now() - interval '52 hours'),
    ('815a0099-d242-5e39-9446-1981cfa09922', '55cc6e9e-6413-58bc-88b6-6342579d8413', '46dec3d5-4cfe-5979-9904-76226e15a7a3', '16259545-f97c-531d-b9cd-6ba115379372', 'admission', 'Przyjęcie - przeniesienie', 'Pacjentka przeniesiona z innego ośrodka z powodu zaburzeń elektrolitowych w przebiegu przewlekłej choroby nerek. Stan ogólny średni.', now() - interval '172 hours', now() - interval '172 hours'),
    ('5422ecc6-c93a-584b-83f5-8b1982e6c75b', '55cc6e9e-6413-58bc-88b6-6342579d8413', '46dec3d5-4cfe-5979-9904-76226e15a7a3', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', 'nursing', 'Obserwacja pielęgniarska', 'Pacjentka wymaga pomocy przy czynnościach dnia codziennego. Ryzyko upadku - wysokie, zastosowano zabezpieczenia łóżka.', now() - interval '148 hours', now() - interval '148 hours'),
    ('26fc3938-f9d3-5fce-9576-8e05569d38ff', '2350ac70-4b44-51c1-8be3-5b736e27a2c9', '50a79ab6-d77a-52cd-a64a-9851e4ee7f65', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', 'discharge', 'Wypis po appendektomii', 'Zabieg appendektomii laparoskopowej przebiegł bez powikłań. Pacjent w stanie dobrym, rana goi się prawidłowo. Zalecono kontrolę w poradni chirurgicznej za 2 tygodnie.', now() - interval '28 hours', now() - interval '28 hours');

--changeset his-mock:005-clinical-note-symptom context:mock
INSERT INTO clinical_note_symptom (note_id, symptom) VALUES
    ('725473be-5cdf-53a2-b7f0-d9638383648b', 'duszność wysiłkowa'),
    ('725473be-5cdf-53a2-b7f0-d9638383648b', 'obrzęki kończyn dolnych'),
    ('725473be-5cdf-53a2-b7f0-d9638383648b', 'osłabienie'),
    ('3abd19d9-3239-5fd6-95ce-37f7fdd77f5b', 'ból w klatce piersiowej'),
    ('3abd19d9-3239-5fd6-95ce-37f7fdd77f5b', 'duszność'),
    ('3abd19d9-3239-5fd6-95ce-37f7fdd77f5b', 'poty'),
    ('2dfde60d-69bb-5691-a3e2-fe2ce90852d7', 'niedowład połowiczy'),
    ('2dfde60d-69bb-5691-a3e2-fe2ce90852d7', 'zaburzenia mowy'),
    ('bf0e574c-0415-5112-89a0-f578b2235daf', 'utrata przytomności'),
    ('bf0e574c-0415-5112-89a0-f578b2235daf', 'ból głowy'),
    ('bf0e574c-0415-5112-89a0-f578b2235daf', 'ból klatki piersiowej'),
    ('815a0099-d242-5e39-9446-1981cfa09922', 'osłabienie'),
    ('815a0099-d242-5e39-9446-1981cfa09922', 'nudności');

--changeset his-mock:005-admission-discharge-summary-note context:mock
UPDATE admission SET discharge_summary_note_id = '78eab1ac-7d6b-55f6-845e-2c1c06ea5f5d' WHERE id = 'b533774b-cdae-5b5b-b87f-18288131c90c';

--changeset his-mock:005-diagnosis context:mock
INSERT INTO diagnosis (id, patient_id, encounter_id, code_system, code_value, code_display, type, status, diagnosed_at, diagnosed_by_id, notes, created_at, updated_at) VALUES
    ('04bc0ba0-f1c2-5a59-83cf-eef0b98b9078', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', '11b7050d-6f4c-546a-9bf7-da0f024b363e', 'ICD-10', 'I50', 'Niewydolność serca', 'primary', 'active', now() - interval '76 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '76 hours', now() - interval '76 hours'),
    ('cba15990-cca7-5ac1-92a1-acf4cf0490d3', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', '8e39787c-8167-5a41-a5cc-7ee611509865', 'ICD-10', 'I10', 'Nadciśnienie tętnicze samoistne', 'chronic', 'active', now() - interval '9604 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '9604 hours', now() - interval '9604 hours'),
    ('7b9c9069-de5b-5572-a64d-17a4be1649d9', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, 'ICD-10', 'E11', 'Cukrzyca typu 2', 'chronic', 'active', now() - interval '9124 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '9124 hours', now() - interval '9124 hours'),
    ('53cec391-185e-54d9-b1ce-b9f8c4f7d21a', '7466c824-06b6-57f2-8bae-2f20f77d64b6', '2e790042-5ce2-543b-baee-416bf421230d', 'ICD-10', 'I21', 'Ostry zawał serca', 'primary', 'active', now() - interval '28 hours', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', NULL, now() - interval '28 hours', now() - interval '28 hours'),
    ('1e045f37-531e-59f7-9387-c9c3a37156ea', '7466c824-06b6-57f2-8bae-2f20f77d64b6', NULL, 'ICD-10', 'I48', 'Migotanie przedsionków', 'secondary', 'active', now() - interval '28 hours', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', NULL, now() - interval '28 hours', now() - interval '28 hours'),
    ('dac6cff7-4f4e-5e38-97bb-857d0a63c1b8', '7466c824-06b6-57f2-8bae-2f20f77d64b6', NULL, 'ICD-10', 'E78.0', 'Hipercholesterolemia', 'chronic', 'active', now() - interval '12003 hours', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', NULL, now() - interval '12003 hours', now() - interval '12003 hours'),
    ('46241894-5c46-5e94-97b1-4eba2caeb582', '7e25abc6-1c68-5922-8f9b-e5a8d6eeb5c9', NULL, 'ICD-10', 'M54.5', 'Ból okolicy lędźwiowo-krzyżowej', 'primary', 'resolved', now() - interval '4323 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '4323 hours', now() - interval '4323 hours'),
    ('73478cfb-3618-5ad9-a637-28dc06428ee1', 'a8500c41-1152-563d-b249-363417666099', NULL, 'ICD-10', 'I63', 'Zawał mózgu', 'primary', 'active', now() - interval '124 hours', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', NULL, now() - interval '124 hours', now() - interval '124 hours'),
    ('559fdbdd-d15c-5bb8-9852-09e11fab3dd9', 'a8500c41-1152-563d-b249-363417666099', NULL, 'ICD-10', 'I10', 'Nadciśnienie tętnicze samoistne', 'chronic', 'active', now() - interval '21603 hours', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', NULL, now() - interval '21603 hours', now() - interval '21603 hours'),
    ('94787d12-889c-5a60-9cf1-338138e0d924', 'dfb16109-f62b-5791-a571-a3652caa0ea7', NULL, 'ICD-10', 'J18.9', 'Zapalenie płuc, nieokreślone', 'primary', 'resolved', now() - interval '484 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '484 hours', now() - interval '484 hours'),
    ('0179c2fa-9197-5354-96c1-46c1e5cb431d', '50c8f3fa-ea66-581a-9207-f9c4c7131d26', NULL, 'ICD-10', 'S06', 'Uraz wewnątrzczaszkowy', 'primary', 'active', now() - interval '6 hours', 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', NULL, now() - interval '6 hours', now() - interval '6 hours'),
    ('b0e79897-e5c9-5199-9973-ebf4f9eadb3f', 'c04f7300-5f2c-51a2-b2b3-b59149f61c47', NULL, 'ICD-10', 'J45', 'Astma', 'chronic', 'active', now() - interval '24004 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '24004 hours', now() - interval '24004 hours'),
    ('e2372f34-37e6-5c75-8590-28c2aed28707', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', NULL, 'ICD-10', 'K80', 'Kamica żółciowa', 'primary', 'active', now() - interval '52 hours', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', NULL, now() - interval '52 hours', now() - interval '52 hours'),
    ('242e0cc8-db8c-504b-850f-aa01e13a3d91', '264400f6-b776-5be9-98e3-25f9678bf0b6', NULL, 'ICD-10', 'I48', 'Migotanie przedsionków', 'primary', 'active', now() - interval '1084 hours', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', NULL, now() - interval '1084 hours', now() - interval '1084 hours'),
    ('2d7cb68a-70b3-50c6-98b2-4febb72e855e', '55cc6e9e-6413-58bc-88b6-6342579d8413', NULL, 'ICD-10', 'N18', 'Przewlekła choroba nerek', 'primary', 'active', now() - interval '172 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '172 hours', now() - interval '172 hours'),
    ('e619959b-3f53-508f-a3d8-66b8e3790afa', '55cc6e9e-6413-58bc-88b6-6342579d8413', NULL, 'ICD-10', 'I10', 'Nadciśnienie tętnicze samoistne', 'chronic', 'active', now() - interval '48003 hours', '16259545-f97c-531d-b9cd-6ba115379372', NULL, now() - interval '48003 hours', now() - interval '48003 hours'),
    ('bae7efe1-730d-5771-a4f4-ea829c116813', '0f0db024-a3c0-56a5-916d-3acf34a052e5', NULL, 'ICD-10', 'K35', 'Ostre zapalenie wyrostka robaczkowego', 'primary', 'active', now() - interval '3 hours', 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', NULL, now() - interval '3 hours', now() - interval '3 hours'),
    ('abec7601-5c00-5b2d-b9a5-186612cdfa3b', '2350ac70-4b44-51c1-8be3-5b736e27a2c9', NULL, 'ICD-10', 'K35', 'Ostre zapalenie wyrostka robaczkowego', 'primary', 'active', now() - interval '28 hours', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', NULL, now() - interval '28 hours', now() - interval '28 hours');

--changeset his-mock:005-episode-diagnosis context:mock
INSERT INTO episode_diagnosis (episode_id, diagnosis_id) VALUES
    ('f3b18e7b-f083-5fe4-b1fc-f2fb9155af71', '04bc0ba0-f1c2-5a59-83cf-eef0b98b9078'),
    ('86fa2594-b0cd-5013-ad51-6740df08edfd', '53cec391-185e-54d9-b1ce-b9f8c4f7d21a'),
    ('86fa2594-b0cd-5013-ad51-6740df08edfd', '1e045f37-531e-59f7-9387-c9c3a37156ea'),
    ('71573662-b592-52d1-a77f-6d59c8e90b3b', '73478cfb-3618-5ad9-a637-28dc06428ee1'),
    ('1c9c803a-6313-5ca8-9fd2-164da8c41e9a', '94787d12-889c-5a60-9cf1-338138e0d924'),
    ('cf8c0456-61b2-532e-8c4b-a20c44715c71', '0179c2fa-9197-5354-96c1-46c1e5cb431d'),
    ('fa820351-4e18-5332-b96d-12f344095e9c', 'e2372f34-37e6-5c75-8590-28c2aed28707'),
    ('6085edd2-bf5f-5df1-a5bf-d4b5b3faafc6', '242e0cc8-db8c-504b-850f-aa01e13a3d91'),
    ('ab9d991f-932f-58ae-a762-acf23b2e4d25', '2d7cb68a-70b3-50c6-98b2-4febb72e855e');

--changeset his-mock:005-allergy context:mock
INSERT INTO allergy (id, patient_id, substance, category, reaction, severity, status, recorded_at, recorded_by_id, created_at, updated_at) VALUES
    ('d47a6ca4-ffa8-599b-aa74-1ccbe1cd01fc', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', 'Penicylina', 'drug', 'Wstrząs anafilaktyczny', 'life_threatening', 'active', now() - interval '9604 hours', NULL, now() - interval '9604 hours', now() - interval '9604 hours'),
    ('ecc2b979-9210-5e1f-98d6-f69fc0b431c0', '7466c824-06b6-57f2-8bae-2f20f77d64b6', 'Jodowe środki kontrastowe', 'drug', 'Pokrzywka, duszność', 'severe', 'active', now() - interval '14404 hours', NULL, now() - interval '14404 hours', now() - interval '14404 hours'),
    ('e8f4729c-0185-5a02-b3f0-330631e84ca1', '7e25abc6-1c68-5922-8f9b-e5a8d6eeb5c9', 'Ibuprofen', 'drug', 'Wysypka skórna', 'moderate', 'active', now() - interval '4803 hours', NULL, now() - interval '4803 hours', now() - interval '4803 hours'),
    ('8ac6c006-c8e8-57c8-8904-eada502e43b0', 'a8500c41-1152-563d-b249-363417666099', 'Orzeszki ziemne', 'food', 'Obrzęk naczynioruchowy', 'severe', 'active', now() - interval '21603 hours', NULL, now() - interval '21603 hours', now() - interval '21603 hours'),
    ('f382f574-0a08-5548-8ff2-7f8ebe214ee9', 'fc5513b6-647f-51d1-8e7e-35d54d4dc21c', 'Pyłki traw', 'environment', 'Katar sienny, łzawienie', 'mild', 'active', now() - interval '24004 hours', NULL, now() - interval '24004 hours', now() - interval '24004 hours'),
    ('07b61377-5f77-50b8-9e51-73f30f8112f9', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', 'Lateks', 'other', 'Kontaktowe zapalenie skóry', 'mild', 'active', now() - interval '16804 hours', NULL, now() - interval '16804 hours', now() - interval '16804 hours'),
    ('b7015e43-7e8c-5003-8343-3e3c39cb9b5a', '55cc6e9e-6413-58bc-88b6-6342579d8413', 'Penicylina', 'drug', 'Obrzęk krtani', 'life_threatening', 'active', now() - interval '48003 hours', NULL, now() - interval '48003 hours', now() - interval '48003 hours');

--changeset his-mock:005-allergy-atc-code context:mock
INSERT INTO allergy_atc_code (allergy_id, atc_code) VALUES
    ('d47a6ca4-ffa8-599b-aa74-1ccbe1cd01fc', 'J01C'),
    ('ecc2b979-9210-5e1f-98d6-f69fc0b431c0', 'V08'),
    ('e8f4729c-0185-5a02-b3f0-330631e84ca1', 'M01A'),
    ('b7015e43-7e8c-5003-8343-3e3c39cb9b5a', 'J01C');

--changeset his-mock:005-contraindication context:mock
INSERT INTO contraindication (id, patient_id, description, reason, recorded_at) VALUES
    ('2e519c7e-7c13-5e46-87d6-1695878db0bd', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', 'Niesteroidowe leki przeciwzapalne (NLPZ)', 'Niewydolność serca – ryzyko retencji płynów i zaostrzenia objawów', now() - interval '7204 hours'),
    ('ac4096ed-9ed5-5f06-9b92-4ababb6dc0d4', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', 'Antybiotyki beta-laktamowe', 'Udokumentowany wstrząs anafilaktyczny po penicylinie', now() - interval '9604 hours'),
    ('5ef3b7a3-8a53-5f7f-a5ca-d697c7957654', '7466c824-06b6-57f2-8bae-2f20f77d64b6', 'Jodowe środki kontrastowe', 'Ciężka reakcja alergiczna w wywiadzie (pokrzywka, duszność)', now() - interval '14404 hours'),
    ('a8533b3a-a949-58e3-8d95-d5f0cc649138', 'a8500c41-1152-563d-b249-363417666099', 'Leki przeciwzakrzepowe w dawkach pełnych', 'Podwyższone ryzyko krwawienia – wiek podeszły', now() - interval '2163 hours');

--changeset his-mock:005-treatment context:mock
INSERT INTO treatment (id, patient_id, encounter_id, name, type, start_at, end_at, status, description, practitioner_id) VALUES
    ('55a7ceb5-8604-55c6-a24b-274e4f54b05e', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', '11b7050d-6f4c-546a-9bf7-da0f024b363e', 'Furosemid dożylnie', 'pharmacotherapy', now() - interval '76 hours', NULL, 'ongoing', 'Leczenie diuretyczne niewydolności serca.', '16259545-f97c-531d-b9cd-6ba115379372'),
    ('e242a940-498c-521a-b9ed-70cc64d2780f', '7466c824-06b6-57f2-8bae-2f20f77d64b6', '2e790042-5ce2-543b-baee-416bf421230d', 'Angioplastyka wieńcowa ze stentem', 'procedure', now() - interval '28 hours', now() - interval '28 hours', 'completed', 'Implantacja stentu do gałęzi okalającej.', '6a2063f1-ade9-52c8-a1b0-f894c0093d46'),
    ('bc37c2a3-089d-5fda-a3e3-1b2824ec50e9', '7e25abc6-1c68-5922-8f9b-e5a8d6eeb5c9', NULL, 'Fizjoterapia odcinka L-S', 'rehabilitation', now() - interval '4323 hours', now() - interval '3843 hours', 'completed', 'Cykl 10 zabiegów fizjoterapeutycznych.', '16259545-f97c-531d-b9cd-6ba115379372'),
    ('efcf86a9-50d4-500f-9aa1-b7196125443c', 'a8500c41-1152-563d-b249-363417666099', NULL, 'Tromboliza dożylna (rt-PA)', 'pharmacotherapy', now() - interval '124 hours', now() - interval '124 hours', 'completed', 'Leczenie trombolityczne udaru niedokrwiennego.', '0ffcc103-5e1d-5346-aeba-8f9907cce3df'),
    ('eb5a71a8-ea15-599b-8a06-15ba0bcef136', 'a8500c41-1152-563d-b249-363417666099', NULL, 'Rehabilitacja neurologiczna', 'rehabilitation', now() - interval '100 hours', NULL, 'ongoing', 'Ćwiczenia ruchowe kończyn niedowładnych.', '0ffcc103-5e1d-5346-aeba-8f9907cce3df'),
    ('4951227d-9b61-59b2-b431-3914fde8668d', 'dfb16109-f62b-5791-a571-a3652caa0ea7', NULL, 'Antybiotykoterapia dożylna', 'pharmacotherapy', now() - interval '484 hours', now() - interval '292 hours', 'completed', 'Leczenie zapalenia płuc.', '16259545-f97c-531d-b9cd-6ba115379372'),
    ('d92ef5ee-7f8e-5803-acd2-fc5128146bdf', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', NULL, 'Cholecystektomia laparoskopowa', 'surgery', now() - interval '4 hours', NULL, 'ongoing', 'Planowy zabieg usunięcia pęcherzyka żółciowego.', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e'),
    ('224caf2c-47e7-5e52-8501-6d45e7da934f', '264400f6-b776-5be9-98e3-25f9678bf0b6', NULL, 'Kardiowersja elektryczna', 'procedure', now() - interval '1060 hours', now() - interval '1060 hours', 'completed', 'Przywrócenie rytmu zatokowego.', '6a2063f1-ade9-52c8-a1b0-f894c0093d46'),
    ('34e8173d-8bb8-52c4-a5c1-dd4165eba208', '55cc6e9e-6413-58bc-88b6-6342579d8413', NULL, 'Korekta zaburzeń elektrolitowych', 'pharmacotherapy', now() - interval '172 hours', NULL, 'ongoing', 'Dożylna suplementacja potasu i magnezu.', '16259545-f97c-531d-b9cd-6ba115379372'),
    ('2ec55387-6dbc-5374-9ed4-d6e389ffdf1a', '2350ac70-4b44-51c1-8be3-5b736e27a2c9', NULL, 'Appendektomia laparoskopowa', 'surgery', now() - interval '28 hours', now() - interval '28 hours', 'completed', 'Usunięcie zmienionego zapalnie wyrostka robaczkowego.', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e');
