--liquibase formatted sql
-- GENERATED by apps/his_frontend/scripts/export-mocks, do not edit

--changeset his-mock:006-lab-order context:mock
INSERT INTO lab_order (id, patient_id, encounter_id, ordered_by_id, ordered_at, urgency, fasting, planned_collection_at, diagnosis_code_system, diagnosis_code_value, diagnosis_code_display, clinical_info, notes, status, created_at, updated_at) VALUES
    ('c288e021-f72f-5590-b4ae-87c1ef6b6c08', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '76 hours', 'routine', FALSE, now() - interval '77 hours', NULL, NULL, NULL, 'Kontrola morfologii w trakcie leczenia niewydolności serca.', NULL, 'completed', now() - interval '76 hours', now() - interval '76 hours'),
    ('fec0820a-7381-5b5c-aa10-e8a8812c27d0', '7466c824-06b6-57f2-8bae-2f20f77d64b6', NULL, '6a2063f1-ade9-52c8-a1b0-f894c0093d46', now() - interval '28 hours', 'stat', FALSE, now() - interval '28 hours', NULL, NULL, NULL, 'Podejrzenie ostrego zespołu wieńcowego.', NULL, 'completed', now() - interval '28 hours', now() - interval '28 hours'),
    ('3b52882d-dcb5-5d90-92c2-43b942f9a6a7', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', NULL, '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', now() - interval '52 hours', 'routine', FALSE, now() - interval '53 hours', NULL, NULL, NULL, 'Badania przedoperacyjne przed cholecystektomią.', NULL, 'completed', now() - interval '52 hours', now() - interval '52 hours'),
    ('4762fbd9-5f6c-516a-94fb-4b12d0ac3ada', '0f0db024-a3c0-56a5-916d-3acf34a052e5', NULL, 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', now() - interval '3 hours', 'stat', FALSE, now() - interval '3 hours', NULL, NULL, NULL, 'Ostry ból brzucha, podejrzenie zapalenia wyrostka robaczkowego.', NULL, 'in_progress', now() - interval '3 hours', now() - interval '3 hours'),
    ('dc0fa407-bb9f-5041-ba51-a2eb747701b6', '55cc6e9e-6413-58bc-88b6-6342579d8413', NULL, '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '148 hours', 'urgent', FALSE, now() - interval '148 hours', NULL, NULL, NULL, 'Kontrola elektrolitów w PChN.', NULL, 'completed', now() - interval '148 hours', now() - interval '148 hours'),
    ('b6a0f537-bd2a-5dbe-b944-3786793db028', 'a8500c41-1152-563d-b249-363417666099', NULL, '0ffcc103-5e1d-5346-aeba-8f9907cce3df', now() - interval '124 hours', 'routine', TRUE, now() - interval '101 hours', NULL, NULL, NULL, 'Kontrola glikemii w trakcie hospitalizacji.', NULL, 'scheduled', now() - interval '124 hours', now() - interval '124 hours'),
    ('8651089d-9360-5c5d-b90c-2986ca095295', '50c8f3fa-ea66-581a-9207-f9c4c7131d26', NULL, 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', now() - interval '6 hours', 'stat', FALSE, now() - interval '6 hours', NULL, NULL, NULL, 'Uraz wielonarządowy, ocena krzepnięcia.', NULL, 'ordered', now() - interval '6 hours', now() - interval '6 hours');

--changeset his-mock:006-lab-order-item context:mock
INSERT INTO lab_order_item (id, order_id, test_code, test_name, specimen_id, specimen_type) VALUES
    ('b89404ab-9b9f-5a8d-8fc3-2e3420536fb6', 'c288e021-f72f-5590-b4ae-87c1ef6b6c08', 'MORF', 'Morfologia krwi z rozmazem', NULL, 'blood'),
    ('506976f5-187c-52de-a15b-df12af7b173b', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', 'TROP', 'Troponina I hs', NULL, 'serum'),
    ('4190d834-57d4-5c6f-8506-4a994b244eec', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', 'CKMB', 'CK-MB', NULL, 'serum'),
    ('d3cd6845-f533-5ea7-a496-63e4605f24ea', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', 'MORF', 'Morfologia krwi z rozmazem', NULL, 'blood'),
    ('3f2f6307-be68-5a46-b6fc-87c8c0ea25c3', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', 'INRPT', 'INR/PT', NULL, 'blood'),
    ('1e2fdb6d-f2a3-54a3-b2e6-b57475a10dc1', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', 'APTT', 'APTT', NULL, 'blood'),
    ('250fcac6-148b-5e3b-84cb-982befddc613', '4762fbd9-5f6c-516a-94fb-4b12d0ac3ada', 'MORF', 'Morfologia krwi z rozmazem', NULL, 'blood'),
    ('623216c8-e042-59d5-8858-b0896700c66b', '4762fbd9-5f6c-516a-94fb-4b12d0ac3ada', 'CRP', 'CRP', NULL, 'serum'),
    ('a1e5d18e-385a-52d9-ab8d-16b6d2ed4efc', 'dc0fa407-bb9f-5041-ba51-a2eb747701b6', 'ELEK', 'Elektrolity (Na, K)', NULL, 'serum'),
    ('7468aad3-aa5d-504a-8aff-8a05535e551b', 'b6a0f537-bd2a-5dbe-b944-3786793db028', 'GLU', 'Glukoza na czczo', NULL, 'serum'),
    ('153a6cb1-69c8-5149-8e4d-3c33283f2a46', '8651089d-9360-5c5d-b90c-2986ca095295', 'MORF', 'Morfologia krwi z rozmazem', NULL, 'blood'),
    ('99927eb0-4887-5261-b4fb-64c35f74b57e', '8651089d-9360-5c5d-b90c-2986ca095295', 'DDIMER', 'D-dimery', NULL, 'blood');

--changeset his-mock:006-lab-order-status-change context:mock
INSERT INTO lab_order_status_change (id, order_id, status, at, by_id, note) VALUES
    ('79a31b74-7dd1-5095-9c06-ec5d81ae47b8', 'c288e021-f72f-5590-b4ae-87c1ef6b6c08', 'ordered', now() - interval '76 hours', NULL, NULL),
    ('0168a1a1-5982-523c-a369-1930c4c6d88a', 'c288e021-f72f-5590-b4ae-87c1ef6b6c08', 'specimen_collected', now() - interval '77 hours', NULL, NULL),
    ('3e47d265-3879-5660-a67a-737ebae323cf', 'c288e021-f72f-5590-b4ae-87c1ef6b6c08', 'completed', now() - interval '48 hours', NULL, NULL),
    ('f9718fc4-c55e-5fb1-a798-55e42ed8ef1d', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', 'ordered', now() - interval '28 hours', NULL, NULL),
    ('9cbe0485-dc98-5908-a7d5-a44da58a08fe', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', 'specimen_collected', now() - interval '28 hours', NULL, NULL),
    ('f99487b9-d3c7-5f64-9884-c42e4dd23482', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', 'in_progress', now() - interval '20 hours', NULL, NULL),
    ('58763d0b-c20c-57d5-8d3f-c94c2df8eeed', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', 'completed', now() - interval '19 hours', NULL, NULL),
    ('aaa01a2a-5669-5e07-b78b-5476c21c9c78', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', 'ordered', now() - interval '52 hours', NULL, NULL),
    ('e124de38-9751-5e69-b9bf-4764456012a0', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', 'specimen_collected', now() - interval '53 hours', NULL, NULL),
    ('ca259f9c-d90d-5ed3-95c1-66c7f0397d21', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', 'completed', now() - interval '22 hours', NULL, NULL),
    ('6ad7f6f6-0345-534f-80b0-a82824646932', '4762fbd9-5f6c-516a-94fb-4b12d0ac3ada', 'ordered', now() - interval '3 hours', NULL, NULL),
    ('4f0bee51-164c-5b53-b6da-54418179baeb', '4762fbd9-5f6c-516a-94fb-4b12d0ac3ada', 'specimen_collected', now() - interval '2 hours', NULL, NULL),
    ('98bbb31f-32de-55af-a797-bdecbf42cc31', '4762fbd9-5f6c-516a-94fb-4b12d0ac3ada', 'in_progress', now() - interval '1 hours', NULL, NULL),
    ('788c5359-f199-5cfc-b891-dd2fb66f93ec', 'dc0fa407-bb9f-5041-ba51-a2eb747701b6', 'ordered', now() - interval '148 hours', NULL, NULL),
    ('3a6d541b-4cf2-55f4-b50e-dcd0b537b02d', 'dc0fa407-bb9f-5041-ba51-a2eb747701b6', 'specimen_collected', now() - interval '148 hours', NULL, NULL),
    ('faef1d37-9060-5699-933e-c87235cfdbab', 'dc0fa407-bb9f-5041-ba51-a2eb747701b6', 'completed', now() - interval '112 hours', NULL, NULL),
    ('2749eec6-3f22-5ffe-9817-0a4f155078ff', 'b6a0f537-bd2a-5dbe-b944-3786793db028', 'ordered', now() - interval '124 hours', NULL, NULL),
    ('915bb501-9d93-5122-a269-6ae7b2e6d86a', 'b6a0f537-bd2a-5dbe-b944-3786793db028', 'scheduled', now() - interval '124 hours', NULL, NULL),
    ('8f40aa93-6eab-5999-afea-5f0dda52cbf5', '8651089d-9360-5c5d-b90c-2986ca095295', 'ordered', now() - interval '6 hours', NULL, NULL);

--changeset his-mock:006-lab-result context:mock
INSERT INTO lab_result (id, patient_id, order_id, order_item_id, test_code, test_name, category, collected_at, resulted_at, status, performer_name, comment, reviewed_at, reviewed_by_id) VALUES
    ('e109ca60-f655-5616-bd02-cafe1ba29da4', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', 'c288e021-f72f-5590-b4ae-87c1ef6b6c08', 'b89404ab-9b9f-5a8d-8fc3-2e3420536fb6', 'MORF', 'Morfologia krwi z rozmazem', 'hematology', now() - interval '8764 hours', now() - interval '8738 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('9e8b58b7-dfa2-5c13-aec5-e4cd635d6c67', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, NULL, 'MORF', 'Morfologia krwi z rozmazem', 'hematology', now() - interval '6484 hours', now() - interval '6458 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('6b878afc-337c-5b5b-a4b7-cb9f57fbdf24', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, NULL, 'MORF', 'Morfologia krwi z rozmazem', 'hematology', now() - interval '4323 hours', now() - interval '4297 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('5b2b6465-ec6f-5561-9f75-fc57e7d49939', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, NULL, 'MORF', 'Morfologia krwi z rozmazem', 'hematology', now() - interval '2163 hours', now() - interval '2137 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('f5b4348c-c9e1-575b-993f-6012076bc903', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, NULL, 'MORF', 'Morfologia krwi z rozmazem', 'hematology', now() - interval '724 hours', now() - interval '698 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('8d783c14-9817-5ecd-958d-1115e98f3276', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', 'c288e021-f72f-5590-b4ae-87c1ef6b6c08', 'b89404ab-9b9f-5a8d-8fc3-2e3420536fb6', 'MORF', 'Morfologia krwi z rozmazem', 'hematology', now() - interval '48 hours', now() - interval '46 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('3d0da807-166f-5c65-bbb9-53814ad134dc', 'a8500c41-1152-563d-b249-363417666099', NULL, NULL, 'HBA1C', 'HbA1c', 'biochemistry', now() - interval '7204 hours', now() - interval '7178 hours', 'final', 'lek. med. lab. Bartosz Kowalczyk', NULL, NULL, NULL),
    ('49a31d06-35ec-56c1-a669-1d382e4e9ac3', 'a8500c41-1152-563d-b249-363417666099', NULL, NULL, 'HBA1C', 'HbA1c', 'biochemistry', now() - interval '5043 hours', now() - interval '5017 hours', 'final', 'lek. med. lab. Bartosz Kowalczyk', NULL, NULL, NULL),
    ('1952ea22-5aaf-5506-a731-c64ba4534beb', 'a8500c41-1152-563d-b249-363417666099', NULL, NULL, 'HBA1C', 'HbA1c', 'biochemistry', now() - interval '2883 hours', now() - interval '2857 hours', 'final', 'lek. med. lab. Bartosz Kowalczyk', NULL, NULL, NULL),
    ('99b9ed80-2912-55c2-ab73-349dd2d620d4', 'a8500c41-1152-563d-b249-363417666099', NULL, NULL, 'GLU', 'Glukoza na czczo', 'biochemistry', now() - interval '149 hours', now() - interval '147 hours', 'final', 'lek. med. lab. Bartosz Kowalczyk', NULL, NULL, NULL),
    ('cc27281d-3319-5737-89ad-47efd0247757', 'a8500c41-1152-563d-b249-363417666099', NULL, NULL, 'GLU', 'Glukoza na czczo', 'biochemistry', now() - interval '101 hours', now() - interval '99 hours', 'final', 'lek. med. lab. Bartosz Kowalczyk', NULL, NULL, NULL),
    ('839a2bd4-cef5-5892-b39c-b3d85a4d6e78', '55cc6e9e-6413-58bc-88b6-6342579d8413', NULL, NULL, 'KREA', 'Kreatynina + eGFR', 'biochemistry', now() - interval '4803 hours', now() - interval '4777 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('f704a4c2-b75f-5a82-9c05-07e7c3957550', '55cc6e9e-6413-58bc-88b6-6342579d8413', NULL, NULL, 'KREA', 'Kreatynina + eGFR', 'biochemistry', now() - interval '2163 hours', now() - interval '2137 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('cce215d2-6066-5197-933c-e37c30cbad1a', '55cc6e9e-6413-58bc-88b6-6342579d8413', 'dc0fa407-bb9f-5041-ba51-a2eb747701b6', 'a1e5d18e-385a-52d9-ab8d-16b6d2ed4efc', 'ELEK', 'Elektrolity (Na, K)', 'biochemistry', now() - interval '148 hours', now() - interval '112 hours', 'final', 'lek. med. lab. Alicja Ostrowska', 'Wynik krytyczny - zgłoszono telefonicznie lekarzowi prowadzącemu.', NULL, NULL),
    ('bb2904b7-7576-5707-893b-7373ea050f9f', '55cc6e9e-6413-58bc-88b6-6342579d8413', NULL, NULL, 'KREA', 'Kreatynina + eGFR', 'biochemistry', now() - interval '148 hours', now() - interval '112 hours', 'final', 'lek. med. lab. Alicja Ostrowska', 'Wynik krytyczny - znaczne pogorszenie funkcji nerek.', NULL, NULL),
    ('f581ba19-b12b-56a2-bc2d-f6f1b94b7bd2', '7466c824-06b6-57f2-8bae-2f20f77d64b6', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', '506976f5-187c-52de-a15b-df12af7b173b', 'TROP', 'Troponina I hs', 'biochemistry', now() - interval '26 hours', now() - interval '19 hours', 'final', 'lek. med. lab. Bartosz Kowalczyk', 'Wynik krytyczny, zgodny z ostrym zawałem serca.', NULL, NULL),
    ('4c064430-6633-5621-b233-87d9a6f8f703', '7466c824-06b6-57f2-8bae-2f20f77d64b6', 'fec0820a-7381-5b5c-aa10-e8a8812c27d0', '4190d834-57d4-5c6f-8506-4a994b244eec', 'CKMB', 'CK-MB', 'biochemistry', now() - interval '26 hours', now() - interval '19 hours', 'final', 'lek. med. lab. Bartosz Kowalczyk', NULL, NULL, NULL),
    ('0ea906ae-499c-52f7-8ce3-500b48d71c30', '0f0db024-a3c0-56a5-916d-3acf34a052e5', NULL, NULL, 'CRP', 'CRP', 'biochemistry', now() - interval '2 hours', now() - interval '1 hours', 'preliminary', 'lek. med. lab. Bartosz Kowalczyk', NULL, NULL, NULL),
    ('50310ba9-1250-57ce-95e6-2a39a0623683', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', 'd3cd6845-f533-5ea7-a496-63e4605f24ea', 'MORF', 'Morfologia krwi z rozmazem', 'hematology', now() - interval '53 hours', now() - interval '22 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL),
    ('7ac50c68-b030-5035-8d4e-5f592b367211', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', '3b52882d-dcb5-5d90-92c2-43b942f9a6a7', '3f2f6307-be68-5a46-b6fc-87c8c0ea25c3', 'INRPT', 'INR/PT', 'coagulation', now() - interval '53 hours', now() - interval '22 hours', 'final', 'lek. med. lab. Alicja Ostrowska', NULL, NULL, NULL);

--changeset his-mock:006-lab-observation context:mock
INSERT INTO lab_observation (id, result_id, analyte_code, analyte_name, value_numeric, value_text, unit, ref_low, ref_high, ref_text, flag) VALUES
    ('0330f362-d89d-5f54-b69f-8e7f153abe59', 'e109ca60-f655-5616-bd02-cafe1ba29da4', 'WBC', 'Leukocyty', 7.2, NULL, 'tys/uL', 4, 10, NULL, 'N'),
    ('240de08b-d0fa-5282-95f7-dfebf43ea113', 'e109ca60-f655-5616-bd02-cafe1ba29da4', 'HGB', 'Hemoglobina', 13.8, NULL, 'g/dL', 12, 16, NULL, 'N'),
    ('f9a299d4-b17c-5787-9519-6c1d40302b00', 'e109ca60-f655-5616-bd02-cafe1ba29da4', 'PLT', 'Płytki krwi', 230, NULL, 'tys/uL', 150, 400, NULL, 'N'),
    ('3d157626-f782-5c5d-b5fe-deb049b4fbe2', '9e8b58b7-dfa2-5c13-aec5-e4cd635d6c67', 'WBC', 'Leukocyty', 7.5, NULL, 'tys/uL', 4, 10, NULL, 'N'),
    ('b9682105-d7ca-51fe-8825-706f2246325a', '9e8b58b7-dfa2-5c13-aec5-e4cd635d6c67', 'HGB', 'Hemoglobina', 12.9, NULL, 'g/dL', 12, 16, NULL, 'N'),
    ('2d88c8eb-22b3-5824-ad38-cb825174b739', '9e8b58b7-dfa2-5c13-aec5-e4cd635d6c67', 'PLT', 'Płytki krwi', 245, NULL, 'tys/uL', 150, 400, NULL, 'N'),
    ('4d540b92-efaa-55da-bb4a-e62e9c079ed0', '6b878afc-337c-5b5b-a4b7-cb9f57fbdf24', 'WBC', 'Leukocyty', 8.1, NULL, 'tys/uL', 4, 10, NULL, 'N'),
    ('bcb89c1f-267b-589e-b36c-fd2cd1299b2d', '6b878afc-337c-5b5b-a4b7-cb9f57fbdf24', 'HGB', 'Hemoglobina', 11.8, NULL, 'g/dL', 12, 16, NULL, 'L'),
    ('161205e0-511c-5482-b37d-f92cf85f00c0', '6b878afc-337c-5b5b-a4b7-cb9f57fbdf24', 'PLT', 'Płytki krwi', 210, NULL, 'tys/uL', 150, 400, NULL, 'N'),
    ('8d650dac-0ecd-5aee-a5f0-78680985139c', '5b2b6465-ec6f-5561-9f75-fc57e7d49939', 'WBC', 'Leukocyty', 9, NULL, 'tys/uL', 4, 10, NULL, 'N'),
    ('ba8bf19e-50be-5537-b29c-3515e2332538', '5b2b6465-ec6f-5561-9f75-fc57e7d49939', 'HGB', 'Hemoglobina', 11.2, NULL, 'g/dL', 12, 16, NULL, 'L'),
    ('cf8d09ea-cb76-5fc9-bcc0-9a6205450c2f', '5b2b6465-ec6f-5561-9f75-fc57e7d49939', 'PLT', 'Płytki krwi', 198, NULL, 'tys/uL', 150, 400, NULL, 'N'),
    ('91aa77b7-ac53-5ca2-904d-fe4336d068d1', 'f5b4348c-c9e1-575b-993f-6012076bc903', 'WBC', 'Leukocyty', 8.6, NULL, 'tys/uL', 4, 10, NULL, 'N'),
    ('d7c46d0c-f034-542b-b0c5-1a4da5e19951', 'f5b4348c-c9e1-575b-993f-6012076bc903', 'HGB', 'Hemoglobina', 10.9, NULL, 'g/dL', 12, 16, NULL, 'L'),
    ('0aaaf43a-07f3-5e25-9df3-2bc23d4b09f5', 'f5b4348c-c9e1-575b-993f-6012076bc903', 'PLT', 'Płytki krwi', 205, NULL, 'tys/uL', 150, 400, NULL, 'N'),
    ('5614b013-e65f-508f-afdc-a9d20936e759', '8d783c14-9817-5ecd-958d-1115e98f3276', 'WBC', 'Leukocyty', 9.4, NULL, 'tys/uL', 4, 10, NULL, 'N'),
    ('d08ac164-7c46-570d-811e-1d789d3bc304', '8d783c14-9817-5ecd-958d-1115e98f3276', 'HGB', 'Hemoglobina', 10.3, NULL, 'g/dL', 12, 16, NULL, 'L'),
    ('a089dbb4-dc95-513e-86e0-279d7bae7e8d', '8d783c14-9817-5ecd-958d-1115e98f3276', 'PLT', 'Płytki krwi', 190, NULL, 'tys/uL', 150, 400, NULL, 'N'),
    ('aa72055c-24ad-5312-955a-a51422837afa', '3d0da807-166f-5c65-bbb9-53814ad134dc', 'HBA1C', 'Hemoglobina glikowana', 6.4, NULL, '%', 4, 6, NULL, 'H'),
    ('4fd18170-b5bb-5409-a0a1-e0bb0bc3052f', '49a31d06-35ec-56c1-a669-1d382e4e9ac3', 'HBA1C', 'Hemoglobina glikowana', 6.8, NULL, '%', 4, 6, NULL, 'H'),
    ('546d3733-afce-56f2-91a1-b99dc3b06ce4', '1952ea22-5aaf-5506-a731-c64ba4534beb', 'HBA1C', 'Hemoglobina glikowana', 7.2, NULL, '%', 4, 6, NULL, 'H'),
    ('046d38d4-7e66-5b9c-899b-fbc006da81c4', '99b9ed80-2912-55c2-ab73-349dd2d620d4', 'GLU', 'Glukoza', 178, NULL, 'mg/dL', 70, 99, NULL, 'H'),
    ('1d5b6882-bd49-5ffd-b7d1-dcd47b08b3b2', 'cc27281d-3319-5737-89ad-47efd0247757', 'GLU', 'Glukoza', 155, NULL, 'mg/dL', 70, 99, NULL, 'H'),
    ('642b1296-4a2a-5927-9023-45e06ebaaac9', '839a2bd4-cef5-5892-b39c-b3d85a4d6e78', 'KREA', 'Kreatynina', 1.8, NULL, 'mg/dL', 0.6, 1.2, NULL, 'H'),
    ('869e4b58-4954-5b7d-ba4d-3887531a835d', '839a2bd4-cef5-5892-b39c-b3d85a4d6e78', 'EGFR', 'eGFR', 38, NULL, 'mL/min/1.73m2', 90, 120, NULL, 'L'),
    ('6987fac9-107c-535e-a825-0e3618b5fa03', 'f704a4c2-b75f-5a82-9c05-07e7c3957550', 'KREA', 'Kreatynina', 2.3, NULL, 'mg/dL', 0.6, 1.2, NULL, 'H'),
    ('cedf9226-4f57-5f8a-be37-7cfd6a18e16b', 'f704a4c2-b75f-5a82-9c05-07e7c3957550', 'EGFR', 'eGFR', 27, NULL, 'mL/min/1.73m2', 90, 120, NULL, 'LL'),
    ('190854f6-93f3-5c46-8970-34a592450637', 'cce215d2-6066-5197-933c-e37c30cbad1a', 'NA', 'Sód', 129, NULL, 'mmol/L', 135, 145, NULL, 'LL'),
    ('90db82f3-9d5d-54f1-af64-6db847c3301d', 'cce215d2-6066-5197-933c-e37c30cbad1a', 'K', 'Potas', 6.3, NULL, 'mmol/L', 3.5, 5.1, NULL, 'HH'),
    ('3f507388-cd9f-5203-8158-83547fd15a76', 'bb2904b7-7576-5707-893b-7373ea050f9f', 'KREA', 'Kreatynina', 2.9, NULL, 'mg/dL', 0.6, 1.2, NULL, 'HH'),
    ('22578ee7-e887-50b7-b6b2-d576bb76789c', 'bb2904b7-7576-5707-893b-7373ea050f9f', 'EGFR', 'eGFR', 19, NULL, 'mL/min/1.73m2', 90, 120, NULL, 'LL'),
    ('585e91dd-d170-5cd4-8dd7-8dc4a9d856fb', 'f581ba19-b12b-56a2-bc2d-f6f1b94b7bd2', 'TROP', 'Troponina I hs', 4520, NULL, 'ng/L', 0, 14, NULL, 'HH'),
    ('a47a3e0d-02cf-5ccf-b719-cf0722fa29d5', '4c064430-6633-5621-b233-87d9a6f8f703', 'CKMB', 'CK-MB', 78, NULL, 'U/L', 0, 25, NULL, 'HH'),
    ('90f2c621-497a-5da5-ad0a-0bf17eb6ccc1', '0ea906ae-499c-52f7-8ce3-500b48d71c30', 'CRP', 'Białko C-reaktywne', 62, NULL, 'mg/L', 0, 5, NULL, 'H'),
    ('709aab08-1ca6-5e9f-9ef2-e3e0edc1a4ab', '50310ba9-1250-57ce-95e6-2a39a0623683', 'WBC', 'Leukocyty', 6.8, NULL, 'tys/uL', 4, 10, NULL, 'N'),
    ('c298c319-f35c-599a-9091-b6e8cad8ec12', '50310ba9-1250-57ce-95e6-2a39a0623683', 'HGB', 'Hemoglobina', 14.5, NULL, 'g/dL', 12, 16, NULL, 'N'),
    ('bdc163b6-ff2e-51d6-80de-ef08c2a61480', '50310ba9-1250-57ce-95e6-2a39a0623683', 'PLT', 'Płytki krwi', 260, NULL, 'tys/uL', 150, 400, NULL, 'N'),
    ('ebe87e78-95ac-5e2d-b972-8fc6c5ed8045', '7ac50c68-b030-5035-8d4e-5f592b367211', 'INR', 'INR', 1, NULL, '', 0.8, 1.2, NULL, 'N'),
    ('07c44539-eb5e-50fd-9612-34c2714e712e', '7ac50c68-b030-5035-8d4e-5f592b367211', 'PT', 'Czas protrombinowy', 12.5, NULL, 's', 11, 15, NULL, 'N');
