--liquibase formatted sql
-- GENERATED by apps/his_frontend/scripts/export-mocks, do not edit

--changeset his-mock:010-message-thread context:mock
INSERT INTO message_thread (id, subject, patient_id, created_by_id, created_at, last_message_at) VALUES
    ('93e35d57-19fe-573b-8dbf-44f29d69af5c', 'Pacjent Kowalski - dawkowanie furosemidu', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, now() - interval '4 hours', now() - interval '1 hours'),
    ('d287dcc0-bbbf-5998-9a7b-f773cf7f57d1', 'Kontrola po koronarografii', '7466c824-06b6-57f2-8bae-2f20f77d64b6', NULL, now() - interval '5 hours', now() - interval '3 hours'),
    ('28ddda82-8247-5f25-972a-27f6ff75e92c', 'Konsultacja kardiologiczna', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', NULL, now() - interval '22 hours', now() - interval '20 hours'),
    ('aceb453e-e3ac-571e-a371-d221f64bd6a8', 'Rehabilitacja pacjentki po udarze', 'a8500c41-1152-563d-b249-363417666099', NULL, now() - interval '8 hours', now() - interval '6 hours'),
    ('fe922873-864c-5398-8d89-1d5bd2f36622', 'Przygotowanie sali operacyjnej', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', NULL, now() - interval '11 hours', now() - interval '10 hours'),
    ('427acd53-6745-5d54-a697-caf7a351d482', 'Organizacja dyżuru SOR', NULL, NULL, now() - interval '3 hours', now() - interval '2 hours');

--changeset his-mock:010-thread-participant context:mock
INSERT INTO thread_participant (thread_id, staff_id, last_read_at, joined_at) VALUES
    ('93e35d57-19fe-573b-8dbf-44f29d69af5c', '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '3 hours', now() - interval '4 hours'),
    ('93e35d57-19fe-573b-8dbf-44f29d69af5c', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', now() - interval '1 hours', now() - interval '4 hours'),
    ('d287dcc0-bbbf-5998-9a7b-f773cf7f57d1', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', now() - interval '3 hours', now() - interval '5 hours'),
    ('d287dcc0-bbbf-5998-9a7b-f773cf7f57d1', 'f9dd7885-41c2-5cf0-a4ca-2a5b45474502', now() - interval '3 hours', now() - interval '5 hours'),
    ('28ddda82-8247-5f25-972a-27f6ff75e92c', '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '20 hours', now() - interval '22 hours'),
    ('28ddda82-8247-5f25-972a-27f6ff75e92c', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', now() - interval '20 hours', now() - interval '22 hours'),
    ('aceb453e-e3ac-571e-a371-d221f64bd6a8', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', now() - interval '8 hours', now() - interval '8 hours'),
    ('aceb453e-e3ac-571e-a371-d221f64bd6a8', '42fb062f-6dc8-574b-b1bd-fc33c5e4decb', now() - interval '6 hours', now() - interval '8 hours'),
    ('fe922873-864c-5398-8d89-1d5bd2f36622', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', now() - interval '10 hours', now() - interval '11 hours'),
    ('fe922873-864c-5398-8d89-1d5bd2f36622', '570c2cc4-eafe-5082-a1ca-e47097316d3a', now() - interval '10 hours', now() - interval '11 hours'),
    ('427acd53-6745-5d54-a697-caf7a351d482', 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', now() - interval '2 hours', now() - interval '3 hours'),
    ('427acd53-6745-5d54-a697-caf7a351d482', 'fbda300f-3c9a-515b-9a3b-ad2b1a7d9775', now() - interval '2 hours', now() - interval '3 hours');

--changeset his-mock:010-message context:mock
INSERT INTO message (id, thread_id, sender_id, sent_at, body, priority) VALUES
    ('1ad95bbc-cfed-5dc0-bf58-4ac6587e14d0', '93e35d57-19fe-573b-8dbf-44f29d69af5c', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', now() - interval '4 hours', 'Panie doktorze, pacjent Kowalski zgłasza duszność przy zmianie pozycji. Bilans płynów za dobę dodatni.', 'high'),
    ('881b100e-f469-5335-99c0-3dd96c58e7ae', '93e35d57-19fe-573b-8dbf-44f29d69af5c', '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '3 hours', 'Proszę zwiększyć dawkę furosemidu do 40 mg dwa razy dziennie i skontrolować elektrolity jutro rano.', 'normal'),
    ('f6aeb5c1-4a3b-5db2-b42e-b2c860674261', '93e35d57-19fe-573b-8dbf-44f29d69af5c', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', now() - interval '1 hours', 'Dawka podana zgodnie z zaleceniem. Pacjent czuje się lepiej.', 'normal'),
    ('a26956e5-e6c0-5b2f-ba44-cb791d30ccbd', 'd287dcc0-bbbf-5998-9a7b-f773cf7f57d1', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', now() - interval '5 hours', 'Proszę o kontrolę parametrów życiowych co 2h po zabiegu koronarografii.', 'high'),
    ('61427bd7-734a-500f-a0c8-ef9ba5365936', 'd287dcc0-bbbf-5998-9a7b-f773cf7f57d1', 'f9dd7885-41c2-5cf0-a4ca-2a5b45474502', now() - interval '3 hours', 'Parametry stabilne, miejsce wkłucia bez cech krwiaka.', 'normal'),
    ('bffec0a5-ce78-5c39-9422-6d107029525b', '28ddda82-8247-5f25-972a-27f6ff75e92c', '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '22 hours', 'Proszę o pilną konsultację kardiologiczną dla pacjenta z sali 204 - narastające obrzęki.', 'high'),
    ('c5defc4e-7c2e-5a08-b8cf-620bad73e3da', '28ddda82-8247-5f25-972a-27f6ff75e92c', '6a2063f1-ade9-52c8-a1b0-f894c0093d46', now() - interval '20 hours', 'Przyjdę po popołudniowym obchodzie, ok. godz. 15:00.', 'normal'),
    ('7d9145ad-a2df-53a8-aa83-e98113d34450', 'aceb453e-e3ac-571e-a371-d221f64bd6a8', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', now() - interval '8 hours', 'Jak przebiega dzisiejsza rehabilitacja pacjentki Kamińskiej?', 'normal'),
    ('54a964e9-8bdc-50a8-8fd2-5db057c3f08e', 'aceb453e-e3ac-571e-a371-d221f64bd6a8', '42fb062f-6dc8-574b-b1bd-fc33c5e4decb', now() - interval '7 hours', 'Siła mięśniowa kończyny górnej poprawiła się do 4/5. Pacjentka współpracuje bardzo dobrze.', 'normal'),
    ('9c664d08-4d8a-506f-bf12-82fa0460b81c', 'aceb453e-e3ac-571e-a371-d221f64bd6a8', '42fb062f-6dc8-574b-b1bd-fc33c5e4decb', now() - interval '6 hours', 'Proszę o decyzję odnośnie zwiększenia intensywności ćwiczeń od jutra.', 'normal'),
    ('d6c738ab-b7db-52e4-a9ec-5e3b78a4a1c2', 'fe922873-864c-5398-8d89-1d5bd2f36622', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', now() - interval '11 hours', 'Proszę przygotować salę operacyjną nr 2 na jutro godz. 8:00, cholecystektomia laparoskopowa.', 'normal'),
    ('a9dc28ed-a2a7-50a5-aab6-bc99521d0b62', 'fe922873-864c-5398-8d89-1d5bd2f36622', '570c2cc4-eafe-5082-a1ca-e47097316d3a', now() - interval '10 hours', 'Sala przygotowana, pacjent poinformowany o zabiegu.', 'normal'),
    ('ab40b6b2-5d4d-5bda-942a-cec67f04e750', '427acd53-6745-5d54-a697-caf7a351d482', 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', now() - interval '3 hours', 'Kto obejmuje dyżur nocny na SOR w ten weekend?', 'normal'),
    ('c6a6149d-3cdc-5347-943d-ce88eca3d6ff', '427acd53-6745-5d54-a697-caf7a351d482', 'fbda300f-3c9a-515b-9a3b-ad2b1a7d9775', now() - interval '2 hours', 'Ja biorę sobotę, w niedzielę jest pielęgniarka Kaczmarek.', 'normal');

--changeset his-mock:010-clinical-alert context:mock
INSERT INTO clinical_alert (id, type, severity, patient_id, message, created_at, target_kind, target_id, target_patient_id) VALUES
    ('fbdd048e-8b29-5846-9cb1-f66a2ae200da', 'critical_result', 'critical', '7466c824-06b6-57f2-8bae-2f20f77d64b6', 'Krytyczny wynik troponiny I hs (4520 ng/L) - pacjentka Maria Wiśniewska.', now() - interval '19 hours', 'lab_result', 'f581ba19-b12b-56a2-bc2d-f6f1b94b7bd2', '7466c824-06b6-57f2-8bae-2f20f77d64b6'),
    ('cfc4bcf6-b56a-5de8-8324-2151f2649eb0', 'critical_result', 'critical', '55cc6e9e-6413-58bc-88b6-6342579d8413', 'Krytyczne stężenie potasu (6.3 mmol/L) - pacjentka Irena Mazur.', now() - interval '20 hours', 'lab_result', 'cce215d2-6066-5197-933c-e37c30cbad1a', '55cc6e9e-6413-58bc-88b6-6342579d8413'),
    ('ac8c5aef-7b5e-527d-b890-46ba70d8a106', 'vital_anomaly', 'critical', '50c8f3fa-ea66-581a-9207-f9c4c7131d26', 'Krytyczny spadek SpO2 (89%) - pacjent Andrzej Szymański.', now() - interval '5 hours', 'patient_vitals', '50c8f3fa-ea66-581a-9207-f9c4c7131d26', NULL),
    ('efe21816-c2cf-5367-9702-721e6552a976', 'vital_anomaly', 'warning', '55cc6e9e-6413-58bc-88b6-6342579d8413', 'Wysokie ciśnienie tętnicze (185/110 mmHg) - pacjentka Irena Mazur.', now() - interval '28 hours', NULL, NULL, NULL),
    ('2564e205-fb02-5231-9684-501e969496ca', 'order_status', 'info', '50c8f3fa-ea66-581a-9207-f9c4c7131d26', 'Zakończono badanie TK głowy - wynik dostępny.', now() - interval '4 hours', 'imaging_result', '46b4363a-51a4-5eae-9151-05948f291573', '50c8f3fa-ea66-581a-9207-f9c4c7131d26'),
    ('42b4ded7-1fbe-534e-abf0-12c147e01d99', 'task', 'warning', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', 'Zaległe zadanie: podanie Clexane 40 mg sc.', now() - interval '1 hours', NULL, NULL, NULL);

--changeset his-mock:010-alert-acknowledgement context:mock
INSERT INTO alert_acknowledgement (alert_id, staff_id, acknowledged_at) VALUES
    ('cfc4bcf6-b56a-5de8-8324-2151f2649eb0', '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '19 hours'),
    ('efe21816-c2cf-5367-9702-721e6552a976', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', DEFAULT);

--changeset his-mock:010-team-task context:mock
INSERT INTO team_task (id, title, description, patient_id, assigned_to_id, created_by_id, created_at, updated_at, due_at, priority, status) VALUES
    ('3de0fe1a-0394-54a5-a65f-13fbc4cf68a6', 'Pobrać krew na morfologię - p. Kowalski, sala 204', NULL, 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '5 hours', now() - interval '5 hours', now() + interval '1 hours', 'normal', 'done'),
    ('94b29fa1-7c9e-5182-aab3-bdeceba70201', 'Podać Clexane 40 mg sc o 20:00', 'Pacjentka po zabiegu, profilaktyka przeciwzakrzepowa.', '17a3dd05-d7d5-5211-ba70-0fc6e51cc476', '570c2cc4-eafe-5082-a1ca-e47097316d3a', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', now() - interval '3 hours', now() - interval '3 hours', now() + interval '2 hours', 'high', 'open'),
    ('9411861a-a089-507a-8a0b-c51f67e1ef25', 'Kontrola glikemii co 6h', NULL, 'a8500c41-1152-563d-b249-363417666099', '42fb062f-6dc8-574b-b1bd-fc33c5e4decb', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', now() - interval '20 hours', now() - interval '20 hours', now() + interval '4 hours', 'normal', 'in_progress'),
    ('21e60213-e036-57c6-b9d3-52d4203c6d78', 'Przygotować pacjenta do wypisu', NULL, 'dfb16109-f62b-5791-a571-a3652caa0ea7', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', '16259545-f97c-531d-b9cd-6ba115379372', now() - interval '30 hours', now() - interval '30 hours', NULL, 'normal', 'done'),
    ('6d28cab5-8a7a-521a-b6fb-8cc08ea236b5', 'Zgłosić wynik krytyczny elektrolitów lekarzowi', NULL, '55cc6e9e-6413-58bc-88b6-6342579d8413', '16259545-f97c-531d-b9cd-6ba115379372', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', now() - interval '18 hours', now() - interval '18 hours', now() - interval '17 hours', 'critical', 'done'),
    ('668f9ca2-059c-5a39-b807-466f9a601001', 'Zamówić wózek inwalidzki dla pacjentki', NULL, 'a8500c41-1152-563d-b249-363417666099', '42fb062f-6dc8-574b-b1bd-fc33c5e4decb', '0ffcc103-5e1d-5346-aeba-8f9907cce3df', now() - interval '2 hours', now() - interval '2 hours', now() + interval '20 hours', 'normal', 'open'),
    ('0b3475a3-1af0-5bb6-aa8d-50b7fd8532e0', 'Skontaktować się z rodziną pacjenta z SOR', NULL, '50c8f3fa-ea66-581a-9207-f9c4c7131d26', 'fbda300f-3c9a-515b-9a3b-ad2b1a7d9775', 'fdf3ef3c-c118-5896-aa53-c2eff5aa7a21', now() - interval '5 hours', now() - interval '5 hours', now() + interval '3 hours', 'high', 'open'),
    ('7c4235ed-3313-5f4d-8387-f75a946eab36', 'Przygotować dokumentację do wypisu', NULL, '2350ac70-4b44-51c1-8be3-5b736e27a2c9', '570c2cc4-eafe-5082-a1ca-e47097316d3a', '19d27aee-1c46-5dd5-a0a4-21da1fe3cf3e', now() - interval '15 hours', now() - interval '15 hours', NULL, 'normal', 'in_progress');

--changeset his-mock:010-handoff-note context:mock
INSERT INTO handoff_note (id, ward_id, shift_date, shift, from_id, to_id, created_at, general_notes) VALUES
    ('a186b9a2-556b-58c5-8ca1-087857b97dfa', '25c25490-5067-5aaa-bcf5-5dc23f56588b', CURRENT_DATE, 'day', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', 'f9dd7885-41c2-5cf0-a4ca-2a5b45474502', now() - interval '1 hours', 'Oddział pełny, brak wolnych łóżek. Zwrócić uwagę na pacjentów z ryzykiem upadku.'),
    ('286fa5dc-4237-5c44-abf3-f7e19c180acc', '36877e50-4f0b-5b6c-bc22-983228fe0d83', CURRENT_DATE, 'night', 'f9dd7885-41c2-5cf0-a4ca-2a5b45474502', '625e824c-3b63-51c2-9e56-78cbfd0ff9a5', now() - interval '12 hours', 'Jeden pacjent po zabiegu koronarografii, wymaga monitorowania miejsca wkłucia.'),
    ('ee715576-70bc-552a-a319-be5aede82453', '1839f924-5e1b-5ceb-963f-f2ee1592947a', CURRENT_DATE - 1, 'night', 'fbda300f-3c9a-515b-9a3b-ad2b1a7d9775', '42fb062f-6dc8-574b-b1bd-fc33c5e4decb', now() - interval '28 hours', 'Spokojny dyżur, jeden pacjent urazowy przekazany na oddział chirurgii.');

--changeset his-mock:010-handoff-patient-note context:mock
INSERT INTO handoff_patient_note (handoff_id, patient_id, situation, background, assessment, recommendation) VALUES
    ('a186b9a2-556b-58c5-8ca1-087857b97dfa', 'c078186c-c437-5fa8-8a5b-a6bf8883f8bf', 'Pacjent z zaostrzeniem niewydolności serca, 3. doba hospitalizacji.', 'Wywiad nadciśnienia i cukrzycy typu 2, leczony ambulatoryjnie.', 'Bilans płynów dodatni, obrzęki zmniejszają się po zwiększeniu dawki furosemidu.', 'Kontynuować leczenie diuretyczne, kontrola elektrolitów rano.'),
    ('a186b9a2-556b-58c5-8ca1-087857b97dfa', '55cc6e9e-6413-58bc-88b6-6342579d8413', 'Pacjentka z przewlekłą chorobą nerek, zaburzenia elektrolitowe.', 'Przeniesiona z innego ośrodka 7 dni temu, wysokie ryzyko upadku.', 'Stan stabilny po korekcie potasu, nadal wymaga częstej kontroli.', 'Kontrola elektrolitów co 12h, zabezpieczenia przeciwupadkowe.'),
    ('286fa5dc-4237-5c44-abf3-f7e19c180acc', '7466c824-06b6-57f2-8bae-2f20f77d64b6', 'Pacjentka po angioplastyce ze stentem, 1. doba po zabiegu.', 'Przyjęta z ostrym zespołem wieńcowym, bez powikłań okołozabiegowych.', 'Parametry stabilne, miejsce wkłucia bez cech krwiaka.', 'Kontrola parametrów co 4h, pionizacja zgodnie z zaleceniem lekarskim.'),
    ('ee715576-70bc-552a-a319-be5aede82453', '50c8f3fa-ea66-581a-9207-f9c4c7131d26', 'Pacjent po wypadku komunikacyjnym, triage czerwony.', 'Uraz wielonarządowy, wykonano TK całego ciała.', 'Stan stabilny po wstępnym zaopatrzeniu, obserwacja neurologiczna.', 'Kontynuować obserwację, kontrola TK głowy za 24h.');
