import type { ClinicalAlert } from '../models';
import { hoursAgo } from './mock-utils';

export const ALERTS: ClinicalAlert[] = [
  {
    id: 'alr-001',
    type: 'critical_result',
    severity: 'critical',
    patientId: 'pat-002',
    message: 'Krytyczny wynik troponiny I hs (4520 ng/L) - pacjentka Maria Wiśniewska.',
    createdAt: hoursAgo(19),
    acknowledged: false,
    target: { kind: 'lab_result', id: 'lres-016', patientId: 'pat-002' },
  },
  {
    id: 'alr-002',
    type: 'critical_result',
    severity: 'critical',
    patientId: 'pat-012',
    message: 'Krytyczne stężenie potasu (6.3 mmol/L) - pacjentka Irena Mazur.',
    createdAt: hoursAgo(20),
    acknowledged: true,
    acknowledgedById: 'stf-001',
    acknowledgedAt: hoursAgo(19),
    target: { kind: 'lab_result', id: 'lres-014', patientId: 'pat-012' },
  },
  {
    id: 'alr-003',
    type: 'vital_anomaly',
    severity: 'critical',
    patientId: 'pat-007',
    message: 'Krytyczny spadek SpO2 (89%) - pacjent Andrzej Szymański.',
    createdAt: hoursAgo(5),
    acknowledged: false,
    target: { kind: 'patient_vitals', id: 'pat-007' },
  },
  {
    id: 'alr-004',
    type: 'vital_anomaly',
    severity: 'warning',
    patientId: 'pat-012',
    message: 'Wysokie ciśnienie tętnicze (185/110 mmHg) - pacjentka Irena Mazur.',
    createdAt: hoursAgo(28),
    acknowledged: true,
    acknowledgedById: 'stf-006',
    target: { kind: 'patient_vitals', id: 'pat-012' },
  },
  {
    id: 'alr-005',
    type: 'order_status',
    severity: 'info',
    patientId: 'pat-007',
    message: 'Zakończono badanie TK głowy - wynik dostępny.',
    createdAt: hoursAgo(4),
    acknowledged: false,
    target: { kind: 'imaging_result', id: 'ires-001', patientId: 'pat-007' },
  },
  {
    id: 'alr-006',
    type: 'task',
    severity: 'warning',
    patientId: 'pat-009',
    message: 'Zaległe zadanie: podanie Clexane 40 mg sc.',
    createdAt: hoursAgo(1),
    acknowledged: false,
    target: { kind: 'task', id: 'tsk-002', patientId: 'pat-009' },
  },
];
