import type { Allergy } from '../models';
import { daysAgo } from './mock-utils';

export const ALLERGIES: Allergy[] = [
  {
    id: 'alg-001',
    patientId: 'pat-001',
    substance: 'Penicylina',
    category: 'drug',
    reaction: 'Wstrząs anafilaktyczny',
    severity: 'life_threatening',
    status: 'active',
    recordedAt: daysAgo(400),
    atcCodes: ['J01C'],
  },
  {
    id: 'alg-002',
    patientId: 'pat-002',
    substance: 'Jodowe środki kontrastowe',
    category: 'drug',
    reaction: 'Pokrzywka, duszność',
    severity: 'severe',
    status: 'active',
    recordedAt: daysAgo(600),
    // V08 = ATC group for contrast media, so Agent E can detect a contrast allergy
    // structurally instead of substring-matching the Polish substance name.
    atcCodes: ['V08'],
  },
  {
    id: 'alg-003',
    patientId: 'pat-003',
    substance: 'Ibuprofen',
    category: 'drug',
    reaction: 'Wysypka skórna',
    severity: 'moderate',
    status: 'active',
    recordedAt: daysAgo(200),
    atcCodes: ['M01A'],
  },
  {
    id: 'alg-004',
    patientId: 'pat-004',
    substance: 'Orzeszki ziemne',
    category: 'food',
    reaction: 'Obrzęk naczynioruchowy',
    severity: 'severe',
    status: 'active',
    recordedAt: daysAgo(900),
  },
  {
    id: 'alg-005',
    patientId: 'pat-006',
    substance: 'Pyłki traw',
    category: 'environment',
    reaction: 'Katar sienny, łzawienie',
    severity: 'mild',
    status: 'active',
    recordedAt: daysAgo(1000),
  },
  {
    id: 'alg-006',
    patientId: 'pat-009',
    substance: 'Lateks',
    category: 'other',
    reaction: 'Kontaktowe zapalenie skóry',
    severity: 'mild',
    status: 'active',
    recordedAt: daysAgo(700),
  },
  {
    id: 'alg-007',
    patientId: 'pat-012',
    substance: 'Penicylina',
    category: 'drug',
    reaction: 'Obrzęk krtani',
    severity: 'life_threatening',
    status: 'active',
    recordedAt: daysAgo(2000),
    atcCodes: ['J01C'],
  },
];
