import type { Diagnosis } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const DIAGNOSES: Diagnosis[] = [
  {
    id: 'dx-001',
    patientId: 'pat-001',
    encounterId: 'enc-001',
    code: { system: 'SNOMED', code: '84114007', display: 'Niewydolność serca' },
    type: 'primary',
    status: 'active',
    diagnosedAt: daysAgo(3),
    diagnosedById: 'stf-001',
  },
  {
    id: 'dx-002',
    patientId: 'pat-001',
    encounterId: 'enc-003',
    code: { system: 'SNOMED', code: '38341003', display: 'Nadciśnienie tętnicze samoistne' },
    type: 'chronic',
    status: 'active',
    diagnosedAt: daysAgo(400),
    diagnosedById: 'stf-001',
  },
  {
    id: 'dx-003',
    patientId: 'pat-001',
    code: { system: 'SNOMED', code: '44054006', display: 'Cukrzyca typu 2' },
    type: 'chronic',
    status: 'active',
    diagnosedAt: daysAgo(380),
    diagnosedById: 'stf-001',
  },

  {
    id: 'dx-004',
    patientId: 'pat-002',
    encounterId: 'enc-004',
    code: { system: 'SNOMED', code: '22298006', display: 'Ostry zawał serca' },
    type: 'primary',
    status: 'active',
    diagnosedAt: daysAgo(1),
    diagnosedById: 'stf-002',
  },
  {
    id: 'dx-005',
    patientId: 'pat-002',
    code: { system: 'SNOMED', code: '49436004', display: 'Migotanie przedsionków' },
    type: 'secondary',
    status: 'active',
    diagnosedAt: daysAgo(1),
    diagnosedById: 'stf-002',
  },
  {
    id: 'dx-006',
    patientId: 'pat-002',
    code: { system: 'SNOMED', code: '55822004', display: 'Hipercholesterolemia' },
    type: 'chronic',
    status: 'active',
    diagnosedAt: daysAgo(500),
    diagnosedById: 'stf-002',
  },

  {
    id: 'dx-007',
    patientId: 'pat-003',
    code: { system: 'SNOMED', code: '279039007', display: 'Ból okolicy lędźwiowo-krzyżowej' },
    type: 'primary',
    status: 'resolved',
    diagnosedAt: daysAgo(180),
    diagnosedById: 'stf-001',
  },

  {
    id: 'dx-008',
    patientId: 'pat-004',
    code: { system: 'SNOMED', code: '422504002', display: 'Zawał mózgu' },
    type: 'primary',
    status: 'active',
    diagnosedAt: daysAgo(5),
    diagnosedById: 'stf-004',
  },
  {
    id: 'dx-009',
    patientId: 'pat-004',
    code: { system: 'SNOMED', code: '38341003', display: 'Nadciśnienie tętnicze samoistne' },
    type: 'chronic',
    status: 'active',
    diagnosedAt: daysAgo(900),
    diagnosedById: 'stf-004',
  },

  {
    id: 'dx-010',
    patientId: 'pat-005',
    code: { system: 'SNOMED', code: '233604007', display: 'Zapalenie płuc, nieokreślone' },
    type: 'primary',
    status: 'resolved',
    diagnosedAt: daysAgo(20),
    diagnosedById: 'stf-001',
  },

  {
    id: 'dx-011',
    patientId: 'pat-007',
    code: { system: 'SNOMED', code: '1734006', display: 'Uraz wewnątrzczaszkowy' },
    type: 'primary',
    status: 'active',
    diagnosedAt: hoursAgo(6),
    diagnosedById: 'stf-005',
  },

  {
    id: 'dx-012',
    patientId: 'pat-008',
    code: { system: 'SNOMED', code: '195967001', display: 'Astma' },
    type: 'chronic',
    status: 'active',
    diagnosedAt: daysAgo(1000),
    diagnosedById: 'stf-001',
  },

  {
    id: 'dx-013',
    patientId: 'pat-009',
    code: { system: 'SNOMED', code: '235919008', display: 'Kamica żółciowa' },
    type: 'primary',
    status: 'active',
    diagnosedAt: daysAgo(2),
    diagnosedById: 'stf-003',
  },

  {
    id: 'dx-014',
    patientId: 'pat-011',
    code: { system: 'SNOMED', code: '49436004', display: 'Migotanie przedsionków' },
    type: 'primary',
    status: 'active',
    diagnosedAt: daysAgo(45),
    diagnosedById: 'stf-002',
  },

  {
    id: 'dx-015',
    patientId: 'pat-012',
    code: { system: 'SNOMED', code: '709044004', display: 'Przewlekła choroba nerek' },
    type: 'primary',
    status: 'active',
    diagnosedAt: daysAgo(7),
    diagnosedById: 'stf-001',
  },
  {
    id: 'dx-016',
    patientId: 'pat-012',
    code: { system: 'SNOMED', code: '38341003', display: 'Nadciśnienie tętnicze samoistne' },
    type: 'chronic',
    status: 'active',
    diagnosedAt: daysAgo(2000),
    diagnosedById: 'stf-001',
  },

  {
    id: 'dx-017',
    patientId: 'pat-013',
    code: { system: 'SNOMED', code: '68496003', display: 'Ostre zapalenie wyrostka robaczkowego' },
    type: 'primary',
    status: 'active',
    diagnosedAt: hoursAgo(3),
    diagnosedById: 'stf-005',
  },

  {
    id: 'dx-018',
    patientId: 'pat-015',
    code: { system: 'SNOMED', code: '68496003', display: 'Ostre zapalenie wyrostka robaczkowego' },
    type: 'primary',
    status: 'active',
    diagnosedAt: daysAgo(1),
    diagnosedById: 'stf-003',
  },
];
