import type { Drug } from '../models';

export const DRUGS_PART_1: Drug[] = [
  {
    id: 'drg-001',
    name: 'Polpril',
    activeSubstance: 'Ramipril',
    atcCode: 'C09AA05',
    form: 'tablet',
    strength: '5 mg',
    packageSize: 28,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-002',
    name: 'Amlozek',
    activeSubstance: 'Amlodypina',
    atcCode: 'C08CA01',
    form: 'tablet',
    strength: '5 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-003',
    name: 'Bisocard',
    activeSubstance: 'Bisoprolol',
    atcCode: 'C07AB07',
    form: 'tablet',
    strength: '5 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-004',
    name: 'Metformax',
    activeSubstance: 'Metformina',
    atcCode: 'A10BA02',
    form: 'tablet',
    strength: '850 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'R', 'none'],
    maxDailyDose: { value: 3000, unit: 'mg' },
  },
  {
    id: 'drg-005',
    name: 'Atoris',
    activeSubstance: 'Atorwastatyna',
    atcCode: 'C10AA05',
    form: 'tablet',
    strength: '20 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-006',
    name: 'Polocard',
    activeSubstance: 'Kwas acetylosalicylowy',
    atcCode: 'B01AC06',
    form: 'tablet',
    strength: '75 mg',
    packageSize: 60,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-007',
    name: 'Xarelto',
    activeSubstance: 'Rywaroksaban',
    atcCode: 'B01AF01',
    form: 'tablet',
    strength: '20 mg',
    packageSize: 28,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'B', 'none'],
    interactsWithAtc: ['B01AC06'],
  },
  {
    id: 'drg-008',
    name: 'Clexane',
    activeSubstance: 'Enoksaparyna',
    atcCode: 'B01AB05',
    form: 'injection',
    strength: '40 mg',
    packageSize: 10,
    packageUnit: 'amp.-strzyk.',
    routes: ['sc'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['100%', 'none'],
    interactsWithAtc: ['B01AF01', 'B01AC06'],
  },
  {
    id: 'drg-009',
    name: 'Furosemid',
    activeSubstance: 'Furosemid',
    atcCode: 'C03CA01',
    form: 'tablet',
    strength: '40 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral', 'iv'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-010',
    name: 'Controloc',
    activeSubstance: 'Pantoprazol',
    atcCode: 'A02BC02',
    form: 'tablet',
    strength: '40 mg',
    packageSize: 28,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-011',
    name: 'Augmentin',
    activeSubstance: 'Amoksycylina + kwas klawulanowy',
    atcCode: 'J01CR02',
    form: 'tablet',
    strength: '875/125 mg',
    packageSize: 14,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['100%', 'none'],
  },
  {
    id: 'drg-012',
    name: 'Klacid',
    activeSubstance: 'Klarytromycyna',
    atcCode: 'J01FA09',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 14,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['100%', 'none'],
  },
];
