import type { Drug } from '../models';

export const DRUGS: Drug[] = [
  {
    id: 'drg-001',
    name: 'Polpril',
    activeSubstance: 'Ramipril',
    atcCode: 'C09AA05',
    form: 'tablet',
    strength: '5 mg',
    packageSize: 28,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-002',
    name: 'Amlozek',
    activeSubstance: 'Amlodypina',
    atcCode: 'C08CA01',
    form: 'tablet',
    strength: '5 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-003',
    name: 'Bisocard',
    activeSubstance: 'Bisoprolol',
    atcCode: 'C07AB07',
    form: 'tablet',
    strength: '5 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-004',
    name: 'Metformax',
    activeSubstance: 'Metformina',
    atcCode: 'A10BA02',
    form: 'tablet',
    strength: '850 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'R', 'none'],
    maxDailyDose: { value: 3000, unit: 'mg' },
  },
  {
    id: 'drg-005',
    name: 'Atoris',
    activeSubstance: 'Atorwastatyna',
    atcCode: 'C10AA05',
    form: 'tablet',
    strength: '20 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-006',
    name: 'Polocard',
    activeSubstance: 'Kwas acetylosalicylowy',
    atcCode: 'B01AC06',
    form: 'tablet',
    strength: '75 mg',
    packageSize: 60,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-007',
    name: 'Xarelto',
    activeSubstance: 'Rywaroksaban',
    atcCode: 'B01AF01',
    form: 'tablet',
    strength: '20 mg',
    packageSize: 28,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'B', 'none'],
    interactsWithAtc: ['B01AC06'],
  },
  {
    id: 'drg-008',
    name: 'Clexane',
    activeSubstance: 'Enoksaparyna',
    atcCode: 'B01AB05',
    form: 'injection',
    strength: '40 mg',
    packageSize: 10,
    packageUnit: 'amp.-strzyk.',
    routes: ['sc'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['100%', 'none'],
    interactsWithAtc: ['B01AF01', 'B01AC06'],
  },
  {
    id: 'drg-009',
    name: 'Furosemid',
    activeSubstance: 'Furosemid',
    atcCode: 'C03CA01',
    form: 'tablet',
    strength: '40 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral', 'iv'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-010',
    name: 'Controloc',
    activeSubstance: 'Pantoprazol',
    atcCode: 'A02BC02',
    form: 'tablet',
    strength: '40 mg',
    packageSize: 28,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-011',
    name: 'Augmentin',
    activeSubstance: 'Amoksycylina + kwas klawulanowy',
    atcCode: 'J01CR02',
    form: 'tablet',
    strength: '875/125 mg',
    packageSize: 14,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['100%', 'none'],
  },
  {
    id: 'drg-012',
    name: 'Klacid',
    activeSubstance: 'Klarytromycyna',
    atcCode: 'J01FA09',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 14,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['100%', 'none'],
  },
  {
    id: 'drg-013',
    name: 'Ketonal',
    activeSubstance: 'Ketoprofen',
    atcCode: 'M01AE03',
    form: 'tablet',
    strength: '100 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-014',
    name: 'Paracetamol',
    activeSubstance: 'Paracetamol',
    atcCode: 'N02BE01',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
    maxDailyDose: { value: 4000, unit: 'mg' },
  },
  {
    id: 'drg-015',
    name: 'Pyralgina',
    activeSubstance: 'Metamizol',
    atcCode: 'N02BB02',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral', 'iv'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-016',
    name: 'Ventolin',
    activeSubstance: 'Salbutamol',
    atcCode: 'R03AC02',
    form: 'inhaler',
    strength: '100 mcg/dawkę',
    packageSize: 1,
    packageUnit: 'inhalator',
    routes: ['inhalation'],
    defaultDoseUnit: 'dawka',
    rxOnly: true,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-017',
    name: 'Humalog',
    activeSubstance: 'Insulina lispro',
    atcCode: 'A10AB04',
    form: 'injection',
    strength: '100 j./mL',
    packageSize: 5,
    packageUnit: 'wkłady',
    routes: ['sc'],
    defaultDoseUnit: 'j.',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-018',
    name: 'Letrox',
    activeSubstance: 'Lewotyroksyna',
    atcCode: 'H03AA01',
    form: 'tablet',
    strength: '50 mcg',
    packageSize: 50,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mcg',
    rxOnly: true,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-019',
    name: 'Hydroksyzyna',
    activeSubstance: 'Hydroksyzyna',
    atcCode: 'N05BB01',
    form: 'tablet',
    strength: '25 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-020',
    name: 'Ibuprom',
    activeSubstance: 'Ibuprofen',
    atcCode: 'M01AE01',
    form: 'tablet',
    strength: '400 mg',
    packageSize: 24,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
    maxDailyDose: { value: 1200, unit: 'mg' },
  },
  {
    id: 'drg-021',
    name: 'Apap',
    activeSubstance: 'Paracetamol',
    atcCode: 'N02BE01',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 24,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-022',
    name: 'Nasonex',
    activeSubstance: 'Mometazon',
    atcCode: 'R01AD09',
    form: 'drops',
    strength: '50 mcg/dawkę',
    packageSize: 1,
    packageUnit: 'but.',
    routes: ['topical'],
    defaultDoseUnit: 'dawka',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-023',
    name: 'Zoltar',
    activeSubstance: 'Zolpidem',
    atcCode: 'N05CF02',
    form: 'tablet',
    strength: '10 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-024',
    name: 'Diclac',
    activeSubstance: 'Diklofenak',
    atcCode: 'M01AB05',
    form: 'ointment',
    strength: '1%',
    packageSize: 1,
    packageUnit: 'tuba',
    routes: ['topical'],
    defaultDoseUnit: 'g',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-025',
    name: 'Enterol',
    activeSubstance: 'Saccharomyces boulardii',
    atcCode: 'A07FA02',
    form: 'capsule',
    strength: '250 mg',
    packageSize: 20,
    packageUnit: 'kaps.',
    routes: ['oral'],
    defaultDoseUnit: 'kaps.',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
];
