import type { Drug } from '../models';

export const DRUGS_PART_2: Drug[] = [
  {
    id: 'drg-013',
    name: 'Ketonal',
    activeSubstance: 'Ketoprofen',
    atcCode: 'M01AE03',
    form: 'tablet',
    strength: '100 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-014',
    name: 'Paracetamol',
    activeSubstance: 'Paracetamol',
    atcCode: 'N02BE01',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
    maxDailyDose: { value: 4000, unit: 'mg' },
  },
  {
    id: 'drg-015',
    name: 'Pyralgina',
    activeSubstance: 'Metamizol',
    atcCode: 'N02BB02',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral', 'iv'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-016',
    name: 'Ventolin',
    activeSubstance: 'Salbutamol',
    atcCode: 'R03AC02',
    form: 'inhaler',
    strength: '100 mcg/dawkę',
    packageSize: 1,
    packageUnit: 'inhalator',
    routes: ['inhalation'],
    defaultDoseUnit: 'dawka',
    rxOnly: true,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-017',
    name: 'Humalog',
    activeSubstance: 'Insulina lispro',
    atcCode: 'A10AB04',
    form: 'injection',
    strength: '100 j./mL',
    packageSize: 5,
    packageUnit: 'wkłady',
    routes: ['sc'],
    defaultDoseUnit: 'j.',
    rxOnly: true,
    reimbursementOptions: ['30%', 'none'],
  },
  {
    id: 'drg-018',
    name: 'Letrox',
    activeSubstance: 'Lewotyroksyna',
    atcCode: 'H03AA01',
    form: 'tablet',
    strength: '50 mcg',
    packageSize: 50,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mcg',
    rxOnly: true,
    reimbursementOptions: ['R', 'none'],
  },
  {
    id: 'drg-019',
    name: 'Hydroksyzyna',
    activeSubstance: 'Hydroksyzyna',
    atcCode: 'N05BB01',
    form: 'tablet',
    strength: '25 mg',
    packageSize: 30,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-020',
    name: 'Ibuprom',
    activeSubstance: 'Ibuprofen',
    atcCode: 'M01AE01',
    form: 'tablet',
    strength: '400 mg',
    packageSize: 24,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
    maxDailyDose: { value: 1200, unit: 'mg' },
  },
  {
    id: 'drg-021',
    name: 'Apap',
    activeSubstance: 'Paracetamol',
    atcCode: 'N02BE01',
    form: 'tablet',
    strength: '500 mg',
    packageSize: 24,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-022',
    name: 'Nasonex',
    activeSubstance: 'Mometazon',
    atcCode: 'R01AD09',
    form: 'drops',
    strength: '50 mcg/dawkę',
    packageSize: 1,
    packageUnit: 'but.',
    routes: ['topical'],
    defaultDoseUnit: 'dawka',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-023',
    name: 'Zoltar',
    activeSubstance: 'Zolpidem',
    atcCode: 'N05CF02',
    form: 'tablet',
    strength: '10 mg',
    packageSize: 20,
    packageUnit: 'tabl.',
    routes: ['oral'],
    defaultDoseUnit: 'mg',
    rxOnly: true,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-024',
    name: 'Diclac',
    activeSubstance: 'Diklofenak',
    atcCode: 'M01AB05',
    form: 'ointment',
    strength: '1%',
    packageSize: 1,
    packageUnit: 'tuba',
    routes: ['topical'],
    defaultDoseUnit: 'g',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
  {
    id: 'drg-025',
    name: 'Enterol',
    activeSubstance: 'Saccharomyces boulardii',
    atcCode: 'A07FA02',
    form: 'capsule',
    strength: '250 mg',
    packageSize: 20,
    packageUnit: 'kaps.',
    routes: ['oral'],
    defaultDoseUnit: 'kaps.',
    rxOnly: false,
    reimbursementOptions: ['none'],
  },
];
