import type { Encounter } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const ENCOUNTERS: Encounter[] = [
  {
    id: 'enc-001',
    patientId: 'pat-001',
    type: 'hospitalization',
    status: 'in_progress',
    startAt: daysAgo(3),
    wardId: 'ward-int',
    practitionerId: 'stf-001',
    reason: 'Zaostrzenie niewydolności serca',
    summary: 'Pacjent przyjęty z powodu duszności wysiłkowej i obrzęków kończyn dolnych.',
    episodeId: 'epi-001',
  },
  {
    id: 'enc-002',
    patientId: 'pat-001',
    type: 'consultation',
    status: 'finished',
    startAt: daysAgo(2),
    endAt: daysAgo(2),
    wardId: 'ward-int',
    practitionerId: 'stf-002',
    reason: 'Konsultacja kardiologiczna',
    summary: 'Zalecono modyfikację leczenia moczopędnego.',
    episodeId: 'epi-001',
  },
  {
    id: 'enc-003',
    patientId: 'pat-001',
    type: 'visit',
    status: 'finished',
    startAt: daysAgo(400),
    endAt: daysAgo(400),
    practitionerId: 'stf-001',
    reason: 'Kontrola nadciśnienia tętniczego',
    summary: 'Wizyta kontrolna, ciśnienie wyrównane.',
  },

  {
    id: 'enc-004',
    patientId: 'pat-002',
    type: 'emergency',
    status: 'in_progress',
    startAt: daysAgo(1),
    wardId: 'ward-kar',
    practitionerId: 'stf-002',
    reason: 'Ból w klatce piersiowej',
    summary: 'Pacjentka przyjęta z bólem zamostkowym promieniującym do lewej ręki.',
    episodeId: 'epi-002',
  },
  {
    id: 'enc-005',
    patientId: 'pat-002',
    type: 'consultation',
    status: 'finished',
    startAt: hoursAgo(20),
    endAt: hoursAgo(19),
    practitionerId: 'stf-002',
    reason: 'Ocena po koronarografii',
    summary: 'Stan stabilny po zabiegu.',
    episodeId: 'epi-002',
  },

  {
    id: 'enc-006',
    patientId: 'pat-003',
    type: 'visit',
    status: 'finished',
    startAt: daysAgo(180),
    endAt: daysAgo(180),
    practitionerId: 'stf-001',
    reason: 'Ból okolicy lędźwiowo-krzyżowej',
    summary: 'Zalecono fizjoterapię i leki przeciwbólowe.',
  },

  {
    id: 'enc-007',
    patientId: 'pat-004',
    type: 'hospitalization',
    status: 'in_progress',
    startAt: daysAgo(5),
    wardId: 'ward-neu',
    practitionerId: 'stf-004',
    reason: 'Udar niedokrwienny mózgu',
    summary: 'Pacjentka przyjęta z niedowładem połowiczym prawostronnym.',
    episodeId: 'epi-003',
  },
  {
    id: 'enc-008',
    patientId: 'pat-004',
    type: 'consultation',
    status: 'finished',
    startAt: daysAgo(4),
    endAt: daysAgo(4),
    practitionerId: 'stf-004',
    reason: 'Ocena rehabilitacyjna',
    summary: 'Rozpoczęto rehabilitację ruchową.',
    episodeId: 'epi-003',
  },

  {
    id: 'enc-009',
    patientId: 'pat-005',
    type: 'hospitalization',
    status: 'finished',
    startAt: daysAgo(20),
    endAt: daysAgo(10),
    wardId: 'ward-int',
    practitionerId: 'stf-001',
    reason: 'Zapalenie płuc',
    summary: 'Wypis w stanie ogólnym dobrym po antybiotykoterapii.',
    episodeId: 'epi-004',
  },

  {
    id: 'enc-010',
    patientId: 'pat-007',
    type: 'emergency',
    status: 'in_progress',
    startAt: daysAgo(0),
    wardId: 'ward-sor',
    practitionerId: 'stf-005',
    reason: 'Uraz wielonarządowy',
    summary: 'Pacjent po wypadku komunikacyjnym, triage czerwony.',
    episodeId: 'epi-005',
  },

  {
    id: 'enc-011',
    patientId: 'pat-008',
    type: 'visit',
    status: 'finished',
    startAt: daysAgo(150),
    endAt: daysAgo(150),
    practitionerId: 'stf-001',
    reason: 'Kontrola astmy oskrzelowej',
    summary: 'Dobra kontrola choroby, kontynuacja leczenia wziewnego.',
  },

  {
    id: 'enc-012',
    patientId: 'pat-009',
    type: 'hospitalization',
    status: 'in_progress',
    startAt: daysAgo(2),
    wardId: 'ward-chg',
    practitionerId: 'stf-003',
    reason: 'Przygotowanie do cholecystektomii',
    summary: 'Pacjent przyjęty planowo, wykonano badania przedoperacyjne.',
    episodeId: 'epi-006',
  },

  {
    id: 'enc-013',
    patientId: 'pat-011',
    type: 'hospitalization',
    status: 'finished',
    startAt: daysAgo(45),
    endAt: daysAgo(38),
    wardId: 'ward-kar',
    practitionerId: 'stf-002',
    reason: 'Migotanie przedsionków',
    summary: 'Skuteczna kardiowersja, wypis w rytmie zatokowym.',
    episodeId: 'epi-007',
  },

  {
    id: 'enc-014',
    patientId: 'pat-012',
    type: 'hospitalization',
    status: 'in_progress',
    startAt: daysAgo(7),
    wardId: 'ward-int',
    practitionerId: 'stf-001',
    reason: 'Zaburzenia elektrolitowe',
    summary: 'Pacjentka przeniesiona z innego szpitala celem dalszego leczenia.',
    episodeId: 'epi-008',
  },

  {
    id: 'enc-015',
    patientId: 'pat-013',
    type: 'emergency',
    status: 'in_progress',
    startAt: hoursAgo(3),
    wardId: 'ward-sor',
    practitionerId: 'stf-005',
    reason: 'Ostry ból brzucha',
  },

  {
    id: 'enc-016',
    patientId: 'pat-015',
    type: 'emergency',
    status: 'finished',
    startAt: daysAgo(1),
    endAt: daysAgo(1),
    wardId: 'ward-chg',
    practitionerId: 'stf-003',
    reason: 'Ostre zapalenie wyrostka robaczkowego',
    summary: 'Wykonano appendektomię laparoskopową.',
  },
];
