import type { ImagingOrder } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const IMAGING_ORDERS: ImagingOrder[] = [
  {
    id: 'iord-001',
    patientId: 'pat-007',
    examCode: 'TK-GL',
    examName: 'TK głowy bez kontrastu',
    modality: 'CT',
    bodyRegion: 'Głowa',
    laterality: 'na',
    contrast: false,
    clinicalIndication:
      'Uraz głowy po wypadku komunikacyjnym, ocena krwawienia wewnątrzczaszkowego.',
    urgency: 'stat',
    safety: {
      pregnancy: 'na',
      pacemakerOrImplant: false,
      metalFragments: false,
      contrastAllergy: false,
      claustrophobia: false,
      confirmed: true,
    },
    scheduledAt: hoursAgo(6),
    orderedById: 'stf-005',
    orderedAt: hoursAgo(6),
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: hoursAgo(6) },
      { status: 'scheduled', at: hoursAgo(6) },
      { status: 'completed', at: hoursAgo(5) },
    ],
  },
  {
    id: 'iord-002',
    patientId: 'pat-004',
    examCode: 'RM-GL-K',
    examName: 'RM głowy z kontrastem',
    modality: 'MRI',
    bodyRegion: 'Głowa',
    laterality: 'na',
    contrast: true,
    clinicalIndication: 'Ocena rozległości udaru niedokrwiennego mózgu.',
    urgency: 'urgent',
    safety: {
      pregnancy: 'na',
      pacemakerOrImplant: false,
      metalFragments: false,
      contrastAllergy: false,
      creatinine: 0.9,
      egfr: 78,
      claustrophobia: false,
      confirmed: true,
    },
    scheduledAt: daysAgo(4, 11),
    orderedById: 'stf-004',
    orderedAt: daysAgo(4),
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: daysAgo(4) },
      { status: 'scheduled', at: daysAgo(4) },
      { status: 'completed', at: daysAgo(4, 12) },
    ],
  },
  {
    id: 'iord-003',
    patientId: 'pat-002',
    examCode: 'KORONARO',
    examName: 'Koronarografia',
    modality: 'ANGIOGRAPHY',
    bodyRegion: 'Tętnice wieńcowe',
    laterality: 'na',
    contrast: true,
    clinicalIndication: 'Podejrzenie ostrego zespołu wieńcowego z uniesieniem ST.',
    urgency: 'stat',
    safety: {
      pregnancy: 'na',
      pacemakerOrImplant: false,
      metalFragments: false,
      contrastAllergy: true,
      creatinine: 0.8,
      egfr: 82,
      claustrophobia: false,
      confirmed: true,
    },
    scheduledAt: daysAgo(1, 9),
    orderedById: 'stf-002',
    orderedAt: daysAgo(1),
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: daysAgo(1) },
      { status: 'scheduled', at: daysAgo(1) },
      { status: 'completed', at: hoursAgo(19) },
    ],
  },
  {
    id: 'iord-004',
    patientId: 'pat-009',
    examCode: 'USG-JB',
    examName: 'USG jamy brzusznej',
    modality: 'USG',
    bodyRegion: 'Jama brzuszna',
    laterality: 'na',
    contrast: false,
    clinicalIndication: 'Objawowa kamica żółciowa, kwalifikacja do zabiegu.',
    urgency: 'routine',
    safety: {
      pregnancy: 'na',
      pacemakerOrImplant: false,
      metalFragments: false,
      contrastAllergy: false,
      claustrophobia: false,
      confirmed: true,
    },
    scheduledAt: daysAgo(2, 10),
    orderedById: 'stf-003',
    orderedAt: daysAgo(2),
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: daysAgo(2) },
      { status: 'scheduled', at: daysAgo(2) },
      { status: 'completed', at: daysAgo(2, 11) },
    ],
  },
  {
    id: 'iord-005',
    patientId: 'pat-003',
    examCode: 'RTG-KOL',
    examName: 'RTG stawu kolanowego',
    modality: 'RTG',
    bodyRegion: 'Staw kolanowy',
    laterality: 'right',
    contrast: false,
    clinicalIndication: 'Ból stawu kolanowego prawego po urazie skrętnym.',
    urgency: 'routine',
    safety: {
      pregnancy: 'na',
      pacemakerOrImplant: false,
      metalFragments: false,
      contrastAllergy: false,
      claustrophobia: false,
      confirmed: true,
    },
    orderedById: 'stf-001',
    orderedAt: daysAgo(180),
    status: 'ordered',
    statusHistory: [{ status: 'ordered', at: daysAgo(180) }],
  },
  {
    id: 'iord-006',
    patientId: 'pat-013',
    examCode: 'USG-JB',
    examName: 'USG jamy brzusznej',
    modality: 'USG',
    bodyRegion: 'Jama brzuszna',
    laterality: 'na',
    contrast: false,
    clinicalIndication: 'Ostry ból brzucha, wykluczenie ostrego zapalenia wyrostka robaczkowego.',
    urgency: 'stat',
    safety: {
      pregnancy: 'no',
      pacemakerOrImplant: false,
      metalFragments: false,
      contrastAllergy: false,
      claustrophobia: false,
      confirmed: true,
    },
    orderedById: 'stf-005',
    orderedAt: hoursAgo(2),
    status: 'in_progress',
    statusHistory: [
      { status: 'ordered', at: hoursAgo(2) },
      { status: 'in_progress', at: hoursAgo(1) },
    ],
  },
];
