import type { ImagingExam } from '../models';

export const IMAGING_CATALOG: ImagingExam[] = [
  {
    code: 'USG-JB',
    modality: 'USG',
    name: 'USG jamy brzusznej',
    bodyRegion: 'Jama brzuszna',
    contrastPossible: false,
    requiresLaterality: false,
    durationMinutes: 20,
  },
  {
    code: 'USG-TR',
    modality: 'USG',
    name: 'USG tarczycy',
    bodyRegion: 'Szyja',
    contrastPossible: false,
    requiresLaterality: false,
    durationMinutes: 15,
  },
  {
    code: 'RTG-KL',
    modality: 'RTG',
    name: 'RTG klatki piersiowej PA',
    bodyRegion: 'Klatka piersiowa',
    contrastPossible: false,
    requiresLaterality: false,
    durationMinutes: 10,
  },
  {
    code: 'RTG-KOL',
    modality: 'RTG',
    name: 'RTG stawu kolanowego',
    bodyRegion: 'Staw kolanowy',
    contrastPossible: false,
    requiresLaterality: true,
    durationMinutes: 10,
  },
  {
    code: 'TK-GL',
    modality: 'CT',
    name: 'TK głowy bez kontrastu',
    bodyRegion: 'Głowa',
    contrastPossible: true,
    requiresLaterality: false,
    durationMinutes: 15,
  },
  {
    code: 'TK-KL-K',
    modality: 'CT',
    name: 'TK klatki piersiowej z kontrastem',
    bodyRegion: 'Klatka piersiowa',
    contrastPossible: true,
    requiresLaterality: false,
    preparation: 'Bycie na czczo 4h przed badaniem.',
    durationMinutes: 20,
  },
  {
    code: 'RM-LS',
    modality: 'MRI',
    name: 'RM kręgosłupa L-S',
    bodyRegion: 'Kręgosłup lędźwiowo-krzyżowy',
    contrastPossible: false,
    requiresLaterality: false,
    durationMinutes: 30,
  },
  {
    code: 'RM-GL-K',
    modality: 'MRI',
    name: 'RM głowy z kontrastem',
    bodyRegion: 'Głowa',
    contrastPossible: true,
    requiresLaterality: false,
    durationMinutes: 35,
  },
  {
    code: 'MMG',
    modality: 'MMG',
    name: 'Mammografia',
    bodyRegion: 'Piersi',
    contrastPossible: false,
    requiresLaterality: true,
    durationMinutes: 15,
  },
  {
    code: 'GASTRO',
    modality: 'ENDOSCOPY',
    name: 'Gastroskopia',
    bodyRegion: 'Górny odcinek przewodu pokarmowego',
    contrastPossible: false,
    requiresLaterality: false,
    preparation: 'Bycie na czczo 6h przed badaniem.',
    durationMinutes: 20,
  },
  {
    code: 'KOLONO',
    modality: 'COLONOSCOPY',
    name: 'Kolonoskopia',
    bodyRegion: 'Jelito grube',
    contrastPossible: false,
    requiresLaterality: false,
    preparation: 'Przygotowanie jelita dzień wcześniej (PEG).',
    durationMinutes: 30,
  },
  {
    code: 'KORONARO',
    modality: 'ANGIOGRAPHY',
    name: 'Koronarografia',
    bodyRegion: 'Tętnice wieńcowe',
    contrastPossible: true,
    requiresLaterality: false,
    durationMinutes: 45,
  },
];
