import type { LabOrder } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const LAB_ORDERS: LabOrder[] = [
  {
    id: 'lord-001',
    patientId: 'pat-001',
    orderedById: 'stf-001',
    orderedAt: daysAgo(3),
    items: [{ testCode: 'MORF', testName: 'Morfologia krwi z rozmazem', specimenType: 'blood' }],
    urgency: 'routine',
    fasting: false,
    plannedCollectionAt: daysAgo(3, 7),
    clinicalInfo: 'Kontrola morfologii w trakcie leczenia niewydolności serca.',
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: daysAgo(3) },
      { status: 'specimen_collected', at: daysAgo(3, 7) },
      { status: 'completed', at: daysAgo(2, 12) },
    ],
  },
  {
    id: 'lord-002',
    patientId: 'pat-002',
    orderedById: 'stf-002',
    orderedAt: daysAgo(1),
    items: [
      { testCode: 'TROP', testName: 'Troponina I hs', specimenType: 'serum' },
      { testCode: 'CKMB', testName: 'CK-MB', specimenType: 'serum' },
    ],
    urgency: 'stat',
    fasting: false,
    plannedCollectionAt: daysAgo(1),
    clinicalInfo: 'Podejrzenie ostrego zespołu wieńcowego.',
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: daysAgo(1) },
      { status: 'specimen_collected', at: daysAgo(1) },
      { status: 'in_progress', at: hoursAgo(20) },
      { status: 'completed', at: hoursAgo(19) },
    ],
  },
  {
    id: 'lord-003',
    patientId: 'pat-009',
    orderedById: 'stf-003',
    orderedAt: daysAgo(2),
    items: [
      { testCode: 'MORF', testName: 'Morfologia krwi z rozmazem', specimenType: 'blood' },
      { testCode: 'INRPT', testName: 'INR/PT', specimenType: 'blood' },
      { testCode: 'APTT', testName: 'APTT', specimenType: 'blood' },
    ],
    urgency: 'routine',
    fasting: false,
    plannedCollectionAt: daysAgo(2, 7),
    clinicalInfo: 'Badania przedoperacyjne przed cholecystektomią.',
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: daysAgo(2) },
      { status: 'specimen_collected', at: daysAgo(2, 7) },
      { status: 'completed', at: daysAgo(1, 14) },
    ],
  },
  {
    id: 'lord-004',
    patientId: 'pat-013',
    orderedById: 'stf-005',
    orderedAt: hoursAgo(3),
    items: [
      { testCode: 'MORF', testName: 'Morfologia krwi z rozmazem', specimenType: 'blood' },
      { testCode: 'CRP', testName: 'CRP', specimenType: 'serum' },
    ],
    urgency: 'stat',
    fasting: false,
    plannedCollectionAt: hoursAgo(3),
    clinicalInfo: 'Ostry ból brzucha, podejrzenie zapalenia wyrostka robaczkowego.',
    status: 'in_progress',
    statusHistory: [
      { status: 'ordered', at: hoursAgo(3) },
      { status: 'specimen_collected', at: hoursAgo(2) },
      { status: 'in_progress', at: hoursAgo(1) },
    ],
  },
  {
    id: 'lord-005',
    patientId: 'pat-012',
    orderedById: 'stf-001',
    orderedAt: daysAgo(6),
    items: [{ testCode: 'ELEK', testName: 'Elektrolity (Na, K)', specimenType: 'serum' }],
    urgency: 'urgent',
    fasting: false,
    plannedCollectionAt: daysAgo(6),
    clinicalInfo: 'Kontrola elektrolitów w PChN.',
    status: 'completed',
    statusHistory: [
      { status: 'ordered', at: daysAgo(6) },
      { status: 'specimen_collected', at: daysAgo(6) },
      { status: 'completed', at: daysAgo(5, 20) },
    ],
  },
  {
    id: 'lord-006',
    patientId: 'pat-004',
    orderedById: 'stf-004',
    orderedAt: daysAgo(5),
    items: [{ testCode: 'GLU', testName: 'Glukoza na czczo', specimenType: 'serum' }],
    urgency: 'routine',
    fasting: true,
    plannedCollectionAt: daysAgo(4, 7),
    clinicalInfo: 'Kontrola glikemii w trakcie hospitalizacji.',
    status: 'scheduled',
    statusHistory: [
      { status: 'ordered', at: daysAgo(5) },
      { status: 'scheduled', at: daysAgo(5) },
    ],
  },
  {
    id: 'lord-007',
    patientId: 'pat-007',
    orderedById: 'stf-005',
    orderedAt: hoursAgo(6),
    items: [
      { testCode: 'MORF', testName: 'Morfologia krwi z rozmazem', specimenType: 'blood' },
      { testCode: 'DDIMER', testName: 'D-dimery', specimenType: 'blood' },
    ],
    urgency: 'stat',
    fasting: false,
    plannedCollectionAt: hoursAgo(6),
    clinicalInfo: 'Uraz wielonarządowy, ocena krzepnięcia.',
    status: 'ordered',
    statusHistory: [{ status: 'ordered', at: hoursAgo(6) }],
  },
];
