import type { LabTest } from '../models';

export const LAB_CATALOG: LabTest[] = [
  {
    code: 'MORF',
    loinc: '58410-2',
    name: 'Morfologia krwi z rozmazem',
    category: 'hematology',
    specimenTypes: ['blood'],
    defaultSpecimen: 'blood',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [
      { code: 'WBC', name: 'Leukocyty', unit: 'tys/uL', low: 4.0, high: 10.0 },
      { code: 'RBC', name: 'Erytrocyty', unit: 'mln/uL', low: 4.2, high: 5.4 },
      { code: 'HGB', name: 'Hemoglobina', unit: 'g/dL', low: 12.0, high: 16.0 },
      { code: 'HCT', name: 'Hematokryt', unit: '%', low: 37, high: 47 },
      { code: 'PLT', name: 'Płytki krwi', unit: 'tys/uL', low: 150, high: 400 },
    ],
  },
  {
    code: 'CRP',
    loinc: '1988-5',
    name: 'CRP',
    category: 'biochemistry',
    specimenTypes: ['serum', 'blood'],
    defaultSpecimen: 'serum',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [{ code: 'CRP', name: 'Białko C-reaktywne', unit: 'mg/L', low: 0, high: 5 }],
  },
  {
    code: 'GLU',
    loinc: '2345-7',
    name: 'Glukoza na czczo',
    category: 'biochemistry',
    specimenTypes: ['serum', 'blood'],
    defaultSpecimen: 'serum',
    turnaroundHours: 2,
    fastingRequired: true,
    analytes: [{ code: 'GLU', name: 'Glukoza', unit: 'mg/dL', low: 70, high: 99 }],
  },
  {
    code: 'HBA1C',
    loinc: '4548-4',
    name: 'HbA1c',
    category: 'biochemistry',
    specimenTypes: ['blood'],
    defaultSpecimen: 'blood',
    turnaroundHours: 4,
    fastingRequired: false,
    analytes: [{ code: 'HBA1C', name: 'Hemoglobina glikowana', unit: '%', low: 4.0, high: 6.0 }],
  },
  {
    code: 'KREA',
    loinc: '2160-0',
    name: 'Kreatynina + eGFR',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [
      { code: 'KREA', name: 'Kreatynina', unit: 'mg/dL', low: 0.6, high: 1.2 },
      { code: 'EGFR', name: 'eGFR', unit: 'mL/min/1.73m2', low: 90, high: 120 },
    ],
  },
  {
    code: 'ELEK',
    loinc: '2951-2',
    name: 'Elektrolity (Na, K)',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 1,
    fastingRequired: false,
    analytes: [
      { code: 'NA', name: 'Sód', unit: 'mmol/L', low: 135, high: 145 },
      { code: 'K', name: 'Potas', unit: 'mmol/L', low: 3.5, high: 5.1 },
    ],
  },
  {
    code: 'ALTAST',
    loinc: '1742-6',
    name: 'ALT/AST',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [
      { code: 'ALT', name: 'ALT', unit: 'U/L', low: 7, high: 40 },
      { code: 'AST', name: 'AST', unit: 'U/L', low: 8, high: 40 },
    ],
  },
  {
    code: 'LIPID',
    loinc: '57698-3',
    name: 'Lipidogram',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 4,
    fastingRequired: true,
    analytes: [
      { code: 'CHOL', name: 'Cholesterol całkowity', unit: 'mg/dL', low: 0, high: 200 },
      { code: 'LDL', name: 'Cholesterol LDL', unit: 'mg/dL', low: 0, high: 130 },
      { code: 'HDL', name: 'Cholesterol HDL', unit: 'mg/dL', low: 40, high: 999 },
      { code: 'TG', name: 'Trójglicerydy', unit: 'mg/dL', low: 0, high: 150 },
    ],
  },
  {
    code: 'TSH',
    loinc: '3016-3',
    name: 'TSH',
    category: 'immunology',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 6,
    fastingRequired: false,
    analytes: [{ code: 'TSH', name: 'TSH', unit: 'mIU/L', low: 0.4, high: 4.0 }],
  },
  {
    code: 'TROP',
    loinc: '10839-9',
    name: 'Troponina I hs',
    category: 'biochemistry',
    specimenTypes: ['serum', 'blood'],
    defaultSpecimen: 'serum',
    turnaroundHours: 1,
    fastingRequired: false,
    analytes: [{ code: 'TROP', name: 'Troponina I hs', unit: 'ng/L', low: 0, high: 14 }],
  },
  {
    code: 'DDIMER',
    loinc: '48065-7',
    name: 'D-dimery',
    category: 'coagulation',
    specimenTypes: ['blood'],
    defaultSpecimen: 'blood',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [{ code: 'DDIMER', name: 'D-dimery', unit: 'ug/L', low: 0, high: 500 }],
  },
  {
    code: 'INRPT',
    loinc: '6301-6',
    name: 'INR/PT',
    category: 'coagulation',
    specimenTypes: ['blood'],
    defaultSpecimen: 'blood',
    turnaroundHours: 1,
    fastingRequired: false,
    analytes: [
      { code: 'INR', name: 'INR', unit: '', low: 0.8, high: 1.2 },
      { code: 'PT', name: 'Czas protrombinowy', unit: 's', low: 11, high: 15 },
    ],
  },
  {
    code: 'APTT',
    loinc: '3173-2',
    name: 'APTT',
    category: 'coagulation',
    specimenTypes: ['blood'],
    defaultSpecimen: 'blood',
    turnaroundHours: 1,
    fastingRequired: false,
    analytes: [{ code: 'APTT', name: 'APTT', unit: 's', low: 25, high: 35 }],
  },
  {
    code: 'UROG',
    loinc: '24357-6',
    name: 'Badanie ogólne moczu',
    category: 'urinalysis',
    specimenTypes: ['urine'],
    defaultSpecimen: 'urine',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [{ code: 'LEU', name: 'Leukocyty w moczu', unit: '/pole widzenia', low: 0, high: 5 }],
  },
  {
    code: 'UROC',
    loinc: '630-4',
    name: 'Posiew moczu z antybiogramem',
    category: 'microbiology',
    specimenTypes: ['urine'],
    defaultSpecimen: 'urine',
    turnaroundHours: 48,
    fastingRequired: false,
    analytes: [
      { code: 'CFU', name: 'Jednostki tworzące kolonie', unit: 'CFU/mL', low: 0, high: 10000 },
    ],
  },
  {
    code: 'PCT',
    loinc: '33959-8',
    name: 'Prokalcytonina',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 4,
    fastingRequired: false,
    analytes: [{ code: 'PCT', name: 'Prokalcytonina', unit: 'ng/mL', low: 0, high: 0.5 }],
  },
  {
    code: 'HISTPAT',
    name: 'Badanie histopatologiczne wycinka',
    category: 'pathology',
    specimenTypes: ['tissue'],
    defaultSpecimen: 'tissue',
    turnaroundHours: 168,
    fastingRequired: false,
    analytes: [{ code: 'HISTPAT', name: 'Wynik histopatologiczny', unit: '' }],
  },
  {
    code: 'FE',
    loinc: '2498-4',
    name: 'Żelazo',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 2,
    fastingRequired: true,
    analytes: [{ code: 'FE', name: 'Żelazo', unit: 'ug/dL', low: 60, high: 170 }],
  },
  {
    code: 'CKMB',
    loinc: '13969-1',
    name: 'CK-MB',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [{ code: 'CKMB', name: 'CK-MB', unit: 'U/L', low: 0, high: 25 }],
  },
  {
    code: 'AMYL',
    loinc: '1798-8',
    name: 'Amylaza',
    category: 'biochemistry',
    specimenTypes: ['serum'],
    defaultSpecimen: 'serum',
    turnaroundHours: 2,
    fastingRequired: false,
    analytes: [{ code: 'AMYL', name: 'Amylaza', unit: 'U/L', low: 28, high: 100 }],
  },
];

/** Lab panels: sets of pre-selected test codes shown as one-click buttons in the catalog picker. */
export const LAB_PANELS: { id: string; name: string; testCodes: string[] }[] = [
  {
    id: 'panel-cardio',
    name: 'Profil kardiologiczny',
    testCodes: ['TROP', 'CKMB', 'LIPID', 'ELEK', 'DDIMER'],
  },
  {
    id: 'panel-preop',
    name: 'Pakiet przedoperacyjny',
    testCodes: ['MORF', 'INRPT', 'APTT', 'ELEK', 'KREA', 'UROG'],
  },
  { id: 'panel-diabetes', name: 'Kontrola cukrzycy', testCodes: ['GLU', 'HBA1C', 'LIPID', 'KREA'] },
];
