import type { Patient } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const PATIENTS_PART_2: Patient[] = [
  {
    id: 'pat-007',
    mrn: 'HIS/2026/000007',
    pesel: '75120560693',
    firstName: 'Andrzej',
    lastName: 'Szymański',
    birthDate: '1975-12-05',
    gender: 'male',
    phone: '+48 512 000 007',
    address: {
      street: 'Wąska',
      buildingNumber: '9',
      postalCode: '50-007',
      city: 'Wrocław',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '01', payer: 'NFZ' },
    bloodType: '0+',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: hoursAgo(6),
      wardId: 'ward-sor',
      room: 'SOR-3',
      attendingPhysicianId: 'stf-005',
      triageLevel: 'red',
      reason: 'Uraz wielonarządowy po wypadku komunikacyjnym',
    },
    flags: ['isolation'],
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'pat-008',
    mrn: 'HIS/2026/000008',
    pesel: '60042195722',
    firstName: 'Helena',
    lastName: 'Woźniak',
    birthDate: '1960-04-21',
    gender: 'female',
    phone: '+48 512 000 008',
    address: {
      street: 'Brzozowa',
      buildingNumber: '14',
      postalCode: '90-008',
      city: 'Łódź',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '05', payer: 'NFZ' },
    bloodType: 'A-',
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(150),
    updatedAt: daysAgo(20),
  },
  {
    id: 'pat-009',
    mrn: 'HIS/2026/000009',
    pesel: '52080803952',
    firstName: 'Tadeusz',
    lastName: 'Dąbrowski',
    birthDate: '1952-08-08',
    gender: 'male',
    address: {
      street: 'Miodowa',
      buildingNumber: '2',
      postalCode: '15-009',
      city: 'Białystok',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Anna Dąbrowska',
      relation: 'Córka',
      phone: '+48 512 000 109',
      isLegalGuardian: false,
    },
    insurance: { status: 'active', nfzBranch: '10', payer: 'NFZ' },
    bloodType: 'B-',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(2),
      wardId: 'ward-chg',
      room: '105',
      bed: 'A',
      attendingPhysicianId: 'stf-003',
      reason: 'Przygotowanie do operacji przepukliny',
    },
    flags: ['dnr'],
    createdAt: daysAgo(700),
    updatedAt: hoursAgo(10),
  },
  {
    id: 'pat-010',
    mrn: 'HIS/2026/000010',
    pesel: '88021449244',
    firstName: 'Katarzyna',
    lastName: 'Kozłowska',
    birthDate: '1988-02-14',
    gender: 'female',
    phone: '+48 512 000 010',
    address: {
      street: 'Kasztanowa',
      buildingNumber: '6',
      postalCode: '70-010',
      city: 'Szczecin',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '16', payer: 'NFZ' },
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(80),
    updatedAt: daysAgo(5),
  },
  {
    id: 'pat-011',
    mrn: 'HIS/2026/000011',
    pesel: '44061966778',
    firstName: 'Józef',
    lastName: 'Jankowski',
    birthDate: '1944-06-19',
    gender: 'male',
    address: {
      street: 'Górna',
      buildingNumber: '11',
      postalCode: '25-011',
      city: 'Kielce',
      country: 'Polska',
    },
    insurance: { status: 'inactive', nfzBranch: '13', payer: 'NFZ' },
    bloodType: 'AB+',
    status: 'discharged',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(45),
      wardId: 'ward-kar',
      room: '118',
      bed: 'B',
      attendingPhysicianId: 'stf-002',
      reason: 'Migotanie przedsionków - kontrola rytmu',
      dischargedAt: daysAgo(38),
    },
    flags: [],
    createdAt: daysAgo(1500),
    updatedAt: daysAgo(38),
  },
];
