import type { Patient } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const PATIENTS_PART_1: Patient[] = [
  {
    id: 'pat-001',
    mrn: 'HIS/2026/000001',
    pesel: '68031437976',
    firstName: 'Jan',
    lastName: 'Kowalski',
    birthDate: '1968-03-14',
    gender: 'male',
    phone: '+48 512 000 001',
    email: 'jan.kowalski@example.com',
    address: {
      street: 'Kwiatowa',
      buildingNumber: '12',
      apartmentNumber: '4',
      postalCode: '00-001',
      city: 'Warszawa',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Ewa Kowalska',
      relation: 'Żona',
      phone: '+48 512 000 101',
      isLegalGuardian: false,
    },
    insurance: { status: 'active', nfzBranch: '07', payer: 'NFZ', ewusVerifiedAt: hoursAgo(20) },
    bloodType: 'A+',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(3),
      wardId: 'ward-int',
      room: '204',
      bed: 'A',
      attendingPhysicianId: 'stf-001',
      reason: 'Zaostrzenie niewydolności serca',
      referralNumber: 'SK/2026/1123',
    },
    flags: ['fall_risk'],
    createdAt: daysAgo(400),
    updatedAt: hoursAgo(2),
  },
  {
    id: 'pat-002',
    mrn: 'HIS/2026/000002',
    pesel: '55070245589',
    firstName: 'Maria',
    lastName: 'Wiśniewska',
    birthDate: '1955-07-02',
    gender: 'female',
    phone: '+48 512 000 002',
    address: {
      street: 'Polna',
      buildingNumber: '5',
      postalCode: '30-002',
      city: 'Kraków',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '06', payer: 'NFZ' },
    bloodType: 'B+',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: daysAgo(1),
      wardId: 'ward-kar',
      room: '112',
      bed: 'B',
      attendingPhysicianId: 'stf-002',
      triageLevel: 'orange',
      reason: 'Ból w klatce piersiowej, podejrzenie ACS',
    },
    flags: [],
    createdAt: daysAgo(600),
    updatedAt: hoursAgo(5),
  },
  {
    id: 'pat-003',
    mrn: 'HIS/2026/000003',
    pesel: '82112351753',
    firstName: 'Krzysztof',
    lastName: 'Wójcik',
    birthDate: '1982-11-23',
    gender: 'male',
    phone: '+48 512 000 003',
    address: {
      street: 'Lipowa',
      buildingNumber: '8',
      postalCode: '61-003',
      city: 'Poznań',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '15', payer: 'NFZ' },
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(200),
    updatedAt: daysAgo(30),
  },
  {
    id: 'pat-004',
    mrn: 'HIS/2026/000004',
    pesel: '47013009767',
    firstName: 'Barbara',
    lastName: 'Kamińska',
    birthDate: '1947-01-30',
    gender: 'female',
    phone: '+48 512 000 004',
    address: {
      street: 'Ogrodowa',
      buildingNumber: '3',
      postalCode: '80-004',
      city: 'Gdańsk',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Adam Kamiński',
      relation: 'Syn',
      phone: '+48 512 000 104',
      isLegalGuardian: false,
    },
    insurance: { status: 'active', nfzBranch: '11', payer: 'NFZ' },
    bloodType: 'AB-',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(5),
      wardId: 'ward-neu',
      room: '301',
      bed: 'A',
      attendingPhysicianId: 'stf-004',
      reason: 'Obserwacja po udarze niedokrwiennym mózgu',
    },
    flags: ['fall_risk', 'infection_risk'],
    createdAt: daysAgo(900),
    updatedAt: hoursAgo(8),
  },
  {
    id: 'pat-005',
    mrn: 'HIS/2026/000005',
    pesel: '39090943038',
    firstName: 'Stanisław',
    lastName: 'Lewandowski',
    birthDate: '1939-09-09',
    gender: 'male',
    address: {
      street: 'Krótka',
      buildingNumber: '1',
      postalCode: '20-005',
      city: 'Lublin',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '03', payer: 'NFZ' },
    status: 'discharged',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(20),
      wardId: 'ward-int',
      room: '210',
      bed: 'C',
      attendingPhysicianId: 'stf-001',
      reason: 'Zapalenie płuc',
      dischargedAt: daysAgo(10),
    },
    flags: [],
    createdAt: daysAgo(1200),
    updatedAt: daysAgo(10),
  },
  {
    id: 'pat-006',
    mrn: 'HIS/2026/000006',
    pesel: '91051742623',
    firstName: 'Zofia',
    lastName: 'Zielińska',
    birthDate: '1991-05-17',
    gender: 'female',
    phone: '+48 512 000 006',
    address: {
      street: 'Słoneczna',
      buildingNumber: '20',
      postalCode: '40-006',
      city: 'Katowice',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '12', payer: 'NFZ' },
    status: 'registered',
    flags: [],
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
];
