import type { Patient } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    mrn: 'HIS/2026/000001',
    pesel: '68031437976',
    firstName: 'Jan',
    lastName: 'Kowalski',
    birthDate: '1968-03-14',
    gender: 'male',
    phone: '+48 512 000 001',
    email: 'jan.kowalski@example.com',
    address: {
      street: 'Kwiatowa',
      buildingNumber: '12',
      apartmentNumber: '4',
      postalCode: '00-001',
      city: 'Warszawa',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Ewa Kowalska',
      relation: 'Żona',
      phone: '+48 512 000 101',
      isLegalGuardian: false,
    },
    insurance: { status: 'active', nfzBranch: '07', payer: 'NFZ', ewusVerifiedAt: hoursAgo(20) },
    bloodType: 'A+',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(3),
      wardId: 'ward-int',
      room: '204',
      bed: 'A',
      attendingPhysicianId: 'stf-001',
      reason: 'Zaostrzenie niewydolności serca',
      referralNumber: 'SK/2026/1123',
    },
    flags: ['fall_risk'],
    createdAt: daysAgo(400),
    updatedAt: hoursAgo(2),
  },
  {
    id: 'pat-002',
    mrn: 'HIS/2026/000002',
    pesel: '55070245589',
    firstName: 'Maria',
    lastName: 'Wiśniewska',
    birthDate: '1955-07-02',
    gender: 'female',
    phone: '+48 512 000 002',
    address: {
      street: 'Polna',
      buildingNumber: '5',
      postalCode: '30-002',
      city: 'Kraków',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '06', payer: 'NFZ' },
    bloodType: 'B+',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: daysAgo(1),
      wardId: 'ward-kar',
      room: '112',
      bed: 'B',
      attendingPhysicianId: 'stf-002',
      triageLevel: 'orange',
      reason: 'Ból w klatce piersiowej, podejrzenie ACS',
    },
    flags: [],
    createdAt: daysAgo(600),
    updatedAt: hoursAgo(5),
  },
  {
    id: 'pat-003',
    mrn: 'HIS/2026/000003',
    pesel: '82112351753',
    firstName: 'Krzysztof',
    lastName: 'Wójcik',
    birthDate: '1982-11-23',
    gender: 'male',
    phone: '+48 512 000 003',
    address: {
      street: 'Lipowa',
      buildingNumber: '8',
      postalCode: '61-003',
      city: 'Poznań',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '15', payer: 'NFZ' },
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(200),
    updatedAt: daysAgo(30),
  },
  {
    id: 'pat-004',
    mrn: 'HIS/2026/000004',
    pesel: '47013009767',
    firstName: 'Barbara',
    lastName: 'Kamińska',
    birthDate: '1947-01-30',
    gender: 'female',
    phone: '+48 512 000 004',
    address: {
      street: 'Ogrodowa',
      buildingNumber: '3',
      postalCode: '80-004',
      city: 'Gdańsk',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Adam Kamiński',
      relation: 'Syn',
      phone: '+48 512 000 104',
      isLegalGuardian: false,
    },
    insurance: { status: 'active', nfzBranch: '11', payer: 'NFZ' },
    bloodType: 'AB-',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(5),
      wardId: 'ward-neu',
      room: '301',
      bed: 'A',
      attendingPhysicianId: 'stf-004',
      reason: 'Obserwacja po udarze niedokrwiennym mózgu',
    },
    flags: ['fall_risk', 'infection_risk'],
    createdAt: daysAgo(900),
    updatedAt: hoursAgo(8),
  },
  {
    id: 'pat-005',
    mrn: 'HIS/2026/000005',
    pesel: '39090943038',
    firstName: 'Stanisław',
    lastName: 'Lewandowski',
    birthDate: '1939-09-09',
    gender: 'male',
    address: {
      street: 'Krótka',
      buildingNumber: '1',
      postalCode: '20-005',
      city: 'Lublin',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '03', payer: 'NFZ' },
    status: 'discharged',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(20),
      wardId: 'ward-int',
      room: '210',
      bed: 'C',
      attendingPhysicianId: 'stf-001',
      reason: 'Zapalenie płuc',
      dischargedAt: daysAgo(10),
    },
    flags: [],
    createdAt: daysAgo(1200),
    updatedAt: daysAgo(10),
  },
  {
    id: 'pat-006',
    mrn: 'HIS/2026/000006',
    pesel: '91051742623',
    firstName: 'Zofia',
    lastName: 'Zielińska',
    birthDate: '1991-05-17',
    gender: 'female',
    phone: '+48 512 000 006',
    address: {
      street: 'Słoneczna',
      buildingNumber: '20',
      postalCode: '40-006',
      city: 'Katowice',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '12', payer: 'NFZ' },
    status: 'registered',
    flags: [],
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },
  {
    id: 'pat-007',
    mrn: 'HIS/2026/000007',
    pesel: '75120560693',
    firstName: 'Andrzej',
    lastName: 'Szymański',
    birthDate: '1975-12-05',
    gender: 'male',
    phone: '+48 512 000 007',
    address: {
      street: 'Wąska',
      buildingNumber: '9',
      postalCode: '50-007',
      city: 'Wrocław',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '01', payer: 'NFZ' },
    bloodType: '0+',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: hoursAgo(6),
      wardId: 'ward-sor',
      room: 'SOR-3',
      attendingPhysicianId: 'stf-005',
      triageLevel: 'red',
      reason: 'Uraz wielonarządowy po wypadku komunikacyjnym',
    },
    flags: ['isolation'],
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'pat-008',
    mrn: 'HIS/2026/000008',
    pesel: '60042195722',
    firstName: 'Helena',
    lastName: 'Woźniak',
    birthDate: '1960-04-21',
    gender: 'female',
    phone: '+48 512 000 008',
    address: {
      street: 'Brzozowa',
      buildingNumber: '14',
      postalCode: '90-008',
      city: 'Łódź',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '05', payer: 'NFZ' },
    bloodType: 'A-',
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(150),
    updatedAt: daysAgo(20),
  },
  {
    id: 'pat-009',
    mrn: 'HIS/2026/000009',
    pesel: '52080803952',
    firstName: 'Tadeusz',
    lastName: 'Dąbrowski',
    birthDate: '1952-08-08',
    gender: 'male',
    address: {
      street: 'Miodowa',
      buildingNumber: '2',
      postalCode: '15-009',
      city: 'Białystok',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Anna Dąbrowska',
      relation: 'Córka',
      phone: '+48 512 000 109',
      isLegalGuardian: false,
    },
    insurance: { status: 'active', nfzBranch: '10', payer: 'NFZ' },
    bloodType: 'B-',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(2),
      wardId: 'ward-chg',
      room: '105',
      bed: 'A',
      attendingPhysicianId: 'stf-003',
      reason: 'Przygotowanie do operacji przepukliny',
    },
    flags: ['dnr'],
    createdAt: daysAgo(700),
    updatedAt: hoursAgo(10),
  },
  {
    id: 'pat-010',
    mrn: 'HIS/2026/000010',
    pesel: '88021449244',
    firstName: 'Katarzyna',
    lastName: 'Kozłowska',
    birthDate: '1988-02-14',
    gender: 'female',
    phone: '+48 512 000 010',
    address: {
      street: 'Kasztanowa',
      buildingNumber: '6',
      postalCode: '70-010',
      city: 'Szczecin',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '16', payer: 'NFZ' },
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(80),
    updatedAt: daysAgo(5),
  },
  {
    id: 'pat-011',
    mrn: 'HIS/2026/000011',
    pesel: '44061966778',
    firstName: 'Józef',
    lastName: 'Jankowski',
    birthDate: '1944-06-19',
    gender: 'male',
    address: {
      street: 'Górna',
      buildingNumber: '11',
      postalCode: '25-011',
      city: 'Kielce',
      country: 'Polska',
    },
    insurance: { status: 'inactive', nfzBranch: '13', payer: 'NFZ' },
    bloodType: 'AB+',
    status: 'discharged',
    currentAdmission: {
      admissionType: 'planned',
      admittedAt: daysAgo(45),
      wardId: 'ward-kar',
      room: '118',
      bed: 'B',
      attendingPhysicianId: 'stf-002',
      reason: 'Migotanie przedsionków - kontrola rytmu',
      dischargedAt: daysAgo(38),
    },
    flags: [],
    createdAt: daysAgo(1500),
    updatedAt: daysAgo(38),
  },
  {
    id: 'pat-012',
    mrn: 'HIS/2026/000012',
    pesel: '33102765704',
    firstName: 'Irena',
    lastName: 'Mazur',
    birthDate: '1933-10-27',
    gender: 'female',
    address: {
      street: 'Cicha',
      buildingNumber: '4',
      postalCode: '10-012',
      city: 'Olsztyn',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Karol Mazur',
      relation: 'Wnuk',
      phone: '+48 512 000 112',
      isLegalGuardian: true,
    },
    insurance: { status: 'active', nfzBranch: '14', payer: 'NFZ' },
    bloodType: '0-',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'transfer',
      admittedAt: daysAgo(7),
      wardId: 'ward-int',
      room: '206',
      bed: 'B',
      attendingPhysicianId: 'stf-001',
      reason: 'Przewlekła choroba nerek, zaburzenia elektrolitowe',
    },
    flags: ['fall_risk', 'vip'],
    createdAt: daysAgo(2000),
    updatedAt: hoursAgo(12),
  },
  {
    id: 'pat-013',
    mrn: 'HIS/2026/000013',
    pesel: '01230324175',
    firstName: 'Piotr',
    lastName: 'Kwiatkowski',
    birthDate: '2001-03-03',
    gender: 'male',
    phone: '+48 512 000 013',
    address: {
      street: 'Zielona',
      buildingNumber: '7',
      postalCode: '35-013',
      city: 'Rzeszów',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '09', payer: 'NFZ' },
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: hoursAgo(3),
      wardId: 'ward-sor',
      room: 'SOR-1',
      attendingPhysicianId: 'stf-005',
      triageLevel: 'yellow',
      reason: 'Ostry ból brzucha, podejrzenie zapalenia wyrostka robaczkowego',
    },
    flags: [],
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'pat-014',
    mrn: 'HIS/2026/000014',
    pesel: '96071114225',
    firstName: 'Aleksandra',
    lastName: 'Krawczyk',
    birthDate: '1996-07-11',
    gender: 'female',
    phone: '+48 512 000 014',
    address: {
      street: 'Akacjowa',
      buildingNumber: '15',
      postalCode: '85-014',
      city: 'Bydgoszcz',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '02', payer: 'NFZ' },
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: 'pat-015',
    mrn: 'HIS/2026/000015',
    pesel: null,
    noPeselReason: 'foreigner',
    identityDocument: { type: 'passport', number: 'FF1234567' },
    firstName: 'Oleksandr',
    lastName: 'Bondarenko',
    birthDate: '1985-09-12',
    gender: 'male',
    phone: '+48 512 000 015',
    address: {
      street: 'Nowa',
      buildingNumber: '18',
      postalCode: '00-015',
      city: 'Warszawa',
      country: 'Polska',
    },
    insurance: { status: 'unknown', nfzBranch: '07', payer: 'none' },
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: daysAgo(1),
      wardId: 'ward-chg',
      room: '108',
      bed: 'A',
      attendingPhysicianId: 'stf-003',
      triageLevel: 'orange',
      reason: 'Ostre zapalenie wyrostka robaczkowego',
    },
    flags: [],
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(2),
  },
];
