import type { Patient } from '../models';
import { daysAgo, hoursAgo } from './mock-utils';

export const PATIENTS_PART_3: Patient[] = [
  {
    id: 'pat-012',
    mrn: 'HIS/2026/000012',
    pesel: '33102765704',
    firstName: 'Irena',
    lastName: 'Mazur',
    birthDate: '1933-10-27',
    gender: 'female',
    address: {
      street: 'Cicha',
      buildingNumber: '4',
      postalCode: '10-012',
      city: 'Olsztyn',
      country: 'Polska',
    },
    emergencyContact: {
      fullName: 'Karol Mazur',
      relation: 'Wnuk',
      phone: '+48 512 000 112',
      isLegalGuardian: true,
    },
    insurance: { status: 'active', nfzBranch: '14', payer: 'NFZ' },
    bloodType: '0-',
    status: 'admitted',
    currentAdmission: {
      admissionType: 'transfer',
      admittedAt: daysAgo(7),
      wardId: 'ward-int',
      room: '206',
      bed: 'B',
      attendingPhysicianId: 'stf-001',
      reason: 'Przewlekła choroba nerek, zaburzenia elektrolitowe',
    },
    flags: ['fall_risk', 'vip'],
    createdAt: daysAgo(2000),
    updatedAt: hoursAgo(12),
  },
  {
    id: 'pat-013',
    mrn: 'HIS/2026/000013',
    pesel: '01230324175',
    firstName: 'Piotr',
    lastName: 'Kwiatkowski',
    birthDate: '2001-03-03',
    gender: 'male',
    phone: '+48 512 000 013',
    address: {
      street: 'Zielona',
      buildingNumber: '7',
      postalCode: '35-013',
      city: 'Rzeszów',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '09', payer: 'NFZ' },
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: hoursAgo(3),
      wardId: 'ward-sor',
      room: 'SOR-1',
      attendingPhysicianId: 'stf-005',
      triageLevel: 'yellow',
      reason: 'Ostry ból brzucha, podejrzenie zapalenia wyrostka robaczkowego',
    },
    flags: [],
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(1),
  },
  {
    id: 'pat-014',
    mrn: 'HIS/2026/000014',
    pesel: '96071114225',
    firstName: 'Aleksandra',
    lastName: 'Krawczyk',
    birthDate: '1996-07-11',
    gender: 'female',
    phone: '+48 512 000 014',
    address: {
      street: 'Akacjowa',
      buildingNumber: '15',
      postalCode: '85-014',
      city: 'Bydgoszcz',
      country: 'Polska',
    },
    insurance: { status: 'active', nfzBranch: '02', payer: 'NFZ' },
    status: 'outpatient',
    flags: [],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: 'pat-015',
    mrn: 'HIS/2026/000015',
    pesel: null,
    noPeselReason: 'foreigner',
    identityDocument: { type: 'passport', number: 'FF1234567' },
    firstName: 'Oleksandr',
    lastName: 'Bondarenko',
    birthDate: '1985-09-12',
    gender: 'male',
    phone: '+48 512 000 015',
    address: {
      street: 'Nowa',
      buildingNumber: '18',
      postalCode: '00-015',
      city: 'Warszawa',
      country: 'Polska',
    },
    insurance: { status: 'unknown', nfzBranch: '07', payer: 'none' },
    status: 'admitted',
    currentAdmission: {
      admissionType: 'emergency',
      admittedAt: daysAgo(1),
      wardId: 'ward-chg',
      room: '108',
      bed: 'A',
      attendingPhysicianId: 'stf-003',
      triageLevel: 'orange',
      reason: 'Ostre zapalenie wyrostka robaczkowego',
    },
    flags: [],
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(2),
  },
];
