import type { Prescription } from '../models';
import { daysAgo, daysAhead } from './mock-utils';

export const PRESCRIPTIONS_PART_2: Prescription[] = [
  {
    id: 'rx-005',
    patientId: 'pat-008',
    prescriberId: 'stf-001',
    issuedAt: daysAgo(150),
    validFrom: daysAgo(150).slice(0, 10),
    validUntil: daysAgo(120).slice(0, 10),
    kind: 'e_prescription',
    items: [
      {
        drugId: 'drg-016',
        drugName: 'Ventolin',
        activeSubstance: 'Salbutamol',
        strength: '100 mcg/dawkę',
        form: 'inhaler',
        dosage: {
          dose: 1,
          doseUnit: 'dawka',
          route: 'inhalation',
          frequency: 'PRN',
          durationDays: 30,
          asNeeded: true,
          maxPerDay: 8,
        },
        quantityPackages: 1,
        reimbursement: 'R',
        substitutionAllowed: true,
      },
    ],
    status: 'dispensed',
    accessCode: '3345',
    eRxKey: '9MB80CA7NTUP87W93FO4WS6ZG9MQ4VDRRNP17PEHRKUS',
  },
  {
    id: 'rx-006',
    patientId: 'pat-009',
    prescriberId: 'stf-003',
    issuedAt: daysAgo(2),
    validFrom: daysAgo(2).slice(0, 10),
    validUntil: daysAhead(28).slice(0, 10),
    kind: 'hospital_order',
    items: [
      {
        drugId: 'drg-010',
        drugName: 'Controloc',
        activeSubstance: 'Pantoprazol',
        strength: '40 mg',
        form: 'tablet',
        dosage: {
          dose: 40,
          doseUnit: 'mg',
          route: 'oral',
          frequency: 'QD',
          durationDays: 14,
          asNeeded: false,
          timesOfDay: ['morning'],
        },
        quantityPackages: 1,
        reimbursement: '30%',
        substitutionAllowed: true,
      },
    ],
    status: 'issued',
    accessCode: '9081',
    eRxKey: '3PRH3H3B0CDZHLUWF0S54CS05TB2KZ9YGB19TJWFIH56',
  },
  {
    id: 'rx-007',
    patientId: 'pat-011',
    prescriberId: 'stf-002',
    issuedAt: daysAgo(44),
    validFrom: daysAgo(44).slice(0, 10),
    validUntil: daysAgo(14).slice(0, 10),
    kind: 'hospital_order',
    items: [
      {
        drugId: 'drg-007',
        drugName: 'Xarelto',
        activeSubstance: 'Rywaroksaban',
        strength: '20 mg',
        form: 'tablet',
        dosage: {
          dose: 20,
          doseUnit: 'mg',
          route: 'oral',
          frequency: 'QD',
          durationDays: 30,
          asNeeded: false,
        },
        quantityPackages: 1,
        reimbursement: '30%',
        substitutionAllowed: false,
      },
    ],
    status: 'dispensed',
    accessCode: '2290',
    eRxKey: 'XY08KKUA1CV1ESUNOYQWZOLF5IPMQ7HZPS7WCQ2EUMY6',
  },
  {
    id: 'rx-008',
    patientId: 'pat-012',
    prescriberId: 'stf-001',
    issuedAt: daysAgo(7),
    validFrom: daysAgo(7).slice(0, 10),
    validUntil: daysAhead(23).slice(0, 10),
    kind: 'hospital_order',
    items: [
      {
        drugId: 'drg-009',
        drugName: 'Furosemid',
        activeSubstance: 'Furosemid',
        strength: '40 mg',
        form: 'tablet',
        dosage: {
          dose: 20,
          doseUnit: 'mg',
          route: 'oral',
          frequency: 'QD',
          durationDays: 14,
          asNeeded: false,
        },
        quantityPackages: 1,
        reimbursement: 'R',
        substitutionAllowed: true,
      },
    ],
    status: 'issued',
    accessCode: '6634',
    eRxKey: 'RKHQ1Z7V7SHNWBZ3FQ418EGAE2C6B20NXJOYWD9WKSGN',
    notes: 'Dawka zredukowana ze względu na funkcję nerek.',
  },
];
