import type { StaffMember } from '../models';

export const STAFF: StaffMember[] = [
  {
    id: 'stf-001',
    title: 'lek.',
    firstName: 'Anna',
    lastName: 'Nowak',
    role: 'doctor',
    specialization: 'Choroby wewnętrzne',
    wardId: 'ward-int',
    phone: '+48 601 100 001',
    online: true,
  },
  {
    id: 'stf-002',
    title: 'dr n. med.',
    firstName: 'Piotr',
    lastName: 'Wiśniewski',
    role: 'doctor',
    specialization: 'Kardiologia',
    wardId: 'ward-kar',
    phone: '+48 601 100 002',
    online: true,
  },
  {
    id: 'stf-003',
    title: 'lek.',
    firstName: 'Tomasz',
    lastName: 'Kamiński',
    role: 'doctor',
    specialization: 'Chirurgia ogólna',
    wardId: 'ward-chg',
    phone: '+48 601 100 003',
    online: false,
  },
  {
    id: 'stf-004',
    title: 'lek.',
    firstName: 'Marta',
    lastName: 'Lewandowska',
    role: 'doctor',
    specialization: 'Neurologia',
    wardId: 'ward-neu',
    phone: '+48 601 100 004',
    online: true,
  },
  {
    id: 'stf-005',
    title: 'lek.',
    firstName: 'Paweł',
    lastName: 'Zieliński',
    role: 'doctor',
    specialization: 'Medycyna ratunkowa',
    wardId: 'ward-sor',
    phone: '+48 601 100 005',
    online: true,
  },
  {
    id: 'stf-006',
    title: 'mgr piel.',
    firstName: 'Katarzyna',
    lastName: 'Zielińska',
    role: 'nurse',
    wardId: 'ward-int',
    phone: '+48 601 100 006',
    online: true,
  },
  {
    id: 'stf-007',
    title: 'piel.',
    firstName: 'Magdalena',
    lastName: 'Wójcik',
    role: 'nurse',
    wardId: 'ward-kar',
    phone: '+48 601 100 007',
    online: false,
  },
  {
    id: 'stf-008',
    title: 'piel.',
    firstName: 'Ewa',
    lastName: 'Lewandowska',
    role: 'nurse',
    specialization: 'Pielęgniarka oddziałowa',
    wardId: 'ward-chg',
    phone: '+48 601 100 008',
    online: true,
  },
  {
    id: 'stf-009',
    title: 'piel.',
    firstName: 'Agnieszka',
    lastName: 'Kaczmarek',
    role: 'nurse',
    wardId: 'ward-neu',
    phone: '+48 601 100 009',
    online: true,
  },
  {
    id: 'stf-010',
    title: 'piel.',
    firstName: 'Michał',
    lastName: 'Szymański',
    role: 'nurse',
    wardId: 'ward-sor',
    phone: '+48 601 100 010',
    online: false,
  },
];
