import type { StaffMember } from '../models';

export const STAFF: StaffMember[] = [
  {
    id: 'stf-001',
    employeeId: 'EMP-0001',
    pwz: '2001117',
    accountStatus: 'active',
    title: 'lek.',
    firstName: 'Anna',
    lastName: 'Nowak',
    role: 'doctor',
    specialization: 'Choroby wewnętrzne',
    wardId: 'ward-int',
    phone: '+48 601 100 001',
    online: true,
  },
  {
    id: 'stf-002',
    employeeId: 'EMP-0002',
    pwz: '2002234',
    accountStatus: 'active',
    title: 'dr n. med.',
    firstName: 'Piotr',
    lastName: 'Wiśniewski',
    role: 'doctor',
    specialization: 'Kardiologia',
    wardId: 'ward-kar',
    phone: '+48 601 100 002',
    online: true,
  },
  {
    id: 'stf-003',
    employeeId: 'EMP-0003',
    pwz: '2003351',
    accountStatus: 'active',
    title: 'lek.',
    firstName: 'Tomasz',
    lastName: 'Kamiński',
    role: 'doctor',
    specialization: 'Chirurgia ogólna',
    wardId: 'ward-chg',
    phone: '+48 601 100 003',
    online: false,
  },
  {
    id: 'stf-004',
    employeeId: 'EMP-0004',
    pwz: '2004468',
    accountStatus: 'active',
    title: 'lek.',
    firstName: 'Marta',
    lastName: 'Lewandowska',
    role: 'doctor',
    specialization: 'Neurologia',
    wardId: 'ward-neu',
    phone: '+48 601 100 004',
    online: true,
  },
  {
    id: 'stf-005',
    employeeId: 'EMP-0005',
    pwz: '2005585',
    accountStatus: 'active',
    title: 'lek.',
    firstName: 'Paweł',
    lastName: 'Zieliński',
    role: 'doctor',
    specialization: 'Medycyna ratunkowa',
    wardId: 'ward-sor',
    phone: '+48 601 100 005',
    online: true,
  },
  {
    id: 'stf-006',
    employeeId: 'EMP-0006',
    pwz: '2006702',
    accountStatus: 'active',
    title: 'mgr piel.',
    firstName: 'Katarzyna',
    lastName: 'Zielińska',
    role: 'nurse',
    wardId: 'ward-int',
    phone: '+48 601 100 006',
    online: true,
  },
  {
    id: 'stf-007',
    employeeId: 'EMP-0007',
    pwz: '2007819',
    accountStatus: 'active',
    title: 'piel.',
    firstName: 'Magdalena',
    lastName: 'Wójcik',
    role: 'nurse',
    wardId: 'ward-kar',
    phone: '+48 601 100 007',
    online: false,
  },
  {
    id: 'stf-008',
    employeeId: 'EMP-0008',
    pwz: '2008936',
    accountStatus: 'active',
    title: 'piel.',
    firstName: 'Ewa',
    lastName: 'Lewandowska',
    role: 'nurse',
    specialization: 'Pielęgniarka oddziałowa',
    wardId: 'ward-chg',
    phone: '+48 601 100 008',
    online: true,
  },
  {
    id: 'stf-009',
    employeeId: 'EMP-0009',
    pwz: '2010053',
    accountStatus: 'active',
    title: 'piel.',
    firstName: 'Agnieszka',
    lastName: 'Kaczmarek',
    role: 'nurse',
    wardId: 'ward-neu',
    phone: '+48 601 100 009',
    online: true,
  },
  {
    id: 'stf-010',
    employeeId: 'EMP-0010',
    pwz: '2011170',
    accountStatus: 'active',
    title: 'piel.',
    firstName: 'Michał',
    lastName: 'Szymański',
    role: 'nurse',
    wardId: 'ward-sor',
    phone: '+48 601 100 010',
    online: false,
  },
];
