import type { TeamTask } from '../models';
import { daysAhead, hoursAgo } from './mock-utils';

export const TASKS: TeamTask[] = [
  {
    id: 'tsk-001',
    title: 'Pobrać krew na morfologię - p. Kowalski, sala 204',
    patientId: 'pat-001',
    assignedToId: 'stf-006',
    createdById: 'stf-001',
    createdAt: hoursAgo(5),
    dueAt: hoursAgo(-1),
    priority: 'normal',
    status: 'done',
  },
  {
    id: 'tsk-002',
    title: 'Podać Clexane 40 mg sc o 20:00',
    description: 'Pacjentka po zabiegu, profilaktyka przeciwzakrzepowa.',
    patientId: 'pat-009',
    assignedToId: 'stf-008',
    createdById: 'stf-003',
    createdAt: hoursAgo(3),
    dueAt: hoursAgo(-2),
    priority: 'high',
    status: 'open',
  },
  {
    id: 'tsk-003',
    title: 'Kontrola glikemii co 6h',
    patientId: 'pat-004',
    assignedToId: 'stf-009',
    createdById: 'stf-004',
    createdAt: hoursAgo(20),
    dueAt: hoursAgo(-4),
    priority: 'normal',
    status: 'in_progress',
  },
  {
    id: 'tsk-004',
    title: 'Przygotować pacjenta do wypisu',
    patientId: 'pat-005',
    assignedToId: 'stf-006',
    createdById: 'stf-001',
    createdAt: hoursAgo(30),
    priority: 'normal',
    status: 'done',
  },
  {
    id: 'tsk-005',
    title: 'Zgłosić wynik krytyczny elektrolitów lekarzowi',
    patientId: 'pat-012',
    assignedToId: 'stf-001',
    createdById: 'stf-006',
    createdAt: hoursAgo(18),
    dueAt: hoursAgo(17),
    priority: 'critical',
    status: 'done',
  },
  {
    id: 'tsk-006',
    title: 'Zamówić wózek inwalidzki dla pacjentki',
    patientId: 'pat-004',
    assignedToId: 'stf-009',
    createdById: 'stf-004',
    createdAt: hoursAgo(2),
    dueAt: daysAhead(1),
    priority: 'normal',
    status: 'open',
  },
  {
    id: 'tsk-007',
    title: 'Skontaktować się z rodziną pacjenta z SOR',
    patientId: 'pat-007',
    assignedToId: 'stf-010',
    createdById: 'stf-005',
    createdAt: hoursAgo(5),
    dueAt: hoursAgo(-3),
    priority: 'high',
    status: 'open',
  },
  {
    id: 'tsk-008',
    title: 'Przygotować dokumentację do wypisu',
    patientId: 'pat-015',
    assignedToId: 'stf-008',
    createdById: 'stf-003',
    createdAt: hoursAgo(15),
    priority: 'normal',
    status: 'in_progress',
  },
];
