import type { Treatment } from '../models';
import { daysAgo } from './mock-utils';

export const TREATMENTS: Treatment[] = [
  {
    id: 'trt-001',
    patientId: 'pat-001',
    name: 'Furosemid dożylnie',
    type: 'pharmacotherapy',
    startAt: daysAgo(3),
    status: 'ongoing',
    description: 'Leczenie diuretyczne niewydolności serca.',
    practitionerId: 'stf-001',
  },
  {
    id: 'trt-002',
    patientId: 'pat-002',
    name: 'Angioplastyka wieńcowa ze stentem',
    type: 'procedure',
    startAt: daysAgo(1),
    endAt: daysAgo(1),
    status: 'completed',
    description: 'Implantacja stentu do gałęzi okalającej.',
    practitionerId: 'stf-002',
  },
  {
    id: 'trt-003',
    patientId: 'pat-003',
    name: 'Fizjoterapia odcinka L-S',
    type: 'rehabilitation',
    startAt: daysAgo(180),
    endAt: daysAgo(160),
    status: 'completed',
    description: 'Cykl 10 zabiegów fizjoterapeutycznych.',
    practitionerId: 'stf-001',
  },
  {
    id: 'trt-004',
    patientId: 'pat-004',
    name: 'Tromboliza dożylna (rt-PA)',
    type: 'pharmacotherapy',
    startAt: daysAgo(5),
    endAt: daysAgo(5),
    status: 'completed',
    description: 'Leczenie trombolityczne udaru niedokrwiennego.',
    practitionerId: 'stf-004',
  },
  {
    id: 'trt-005',
    patientId: 'pat-004',
    name: 'Rehabilitacja neurologiczna',
    type: 'rehabilitation',
    startAt: daysAgo(4),
    status: 'ongoing',
    description: 'Ćwiczenia ruchowe kończyn niedowładnych.',
    practitionerId: 'stf-004',
  },
  {
    id: 'trt-006',
    patientId: 'pat-005',
    name: 'Antybiotykoterapia dożylna',
    type: 'pharmacotherapy',
    startAt: daysAgo(20),
    endAt: daysAgo(12),
    status: 'completed',
    description: 'Leczenie zapalenia płuc.',
    practitionerId: 'stf-001',
  },
  {
    id: 'trt-007',
    patientId: 'pat-009',
    name: 'Cholecystektomia laparoskopowa',
    type: 'surgery',
    startAt: daysAgo(0),
    status: 'ongoing',
    description: 'Planowy zabieg usunięcia pęcherzyka żółciowego.',
    practitionerId: 'stf-003',
  },
  {
    id: 'trt-008',
    patientId: 'pat-011',
    name: 'Kardiowersja elektryczna',
    type: 'procedure',
    startAt: daysAgo(44),
    endAt: daysAgo(44),
    status: 'completed',
    description: 'Przywrócenie rytmu zatokowego.',
    practitionerId: 'stf-002',
  },
  {
    id: 'trt-009',
    patientId: 'pat-012',
    name: 'Korekta zaburzeń elektrolitowych',
    type: 'pharmacotherapy',
    startAt: daysAgo(7),
    status: 'ongoing',
    description: 'Dożylna suplementacja potasu i magnezu.',
    practitionerId: 'stf-001',
  },
  {
    id: 'trt-010',
    patientId: 'pat-015',
    name: 'Appendektomia laparoskopowa',
    type: 'surgery',
    startAt: daysAgo(1),
    endAt: daysAgo(1),
    status: 'completed',
    description: 'Usunięcie zmienionego zapalnie wyrostka robaczkowego.',
    practitionerId: 'stf-003',
  },
];
