ARG RUNTIME_VERSION
FROM python:${RUNTIME_VERSION}-slim
RUN apt-get update \
    && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/*
ARG PROJECT_PATH
ARG APP_PORT
ARG START_COMMAND
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY ${PROJECT_PATH}/ ./
ENV START_COMMAND=${START_COMMAND}
EXPOSE ${APP_PORT}
CMD ["sh", "-c", "exec ${START_COMMAND}"]
