import type { Translation } from 'primeng/api';

/**
 * Hand-written Polish translation for PrimeNG components.
 * There is no primelocale package for PrimeNG 21, so this is written by hand
 * against the `Translation` interface exported from `primeng/api`.
 */
export const PRIMENG_PL: Translation = {
  startsWith: 'Zaczyna się od',
  contains: 'Zawiera',
  notContains: 'Nie zawiera',
  endsWith: 'Kończy się na',
  equals: 'Równa się',
  notEquals: 'Różne od',
  noFilter: 'Brak filtra',
  lt: 'Mniejsze niż',
  lte: 'Mniejsze lub równe',
  gt: 'Większe niż',
  gte: 'Większe lub równe',
  is: 'Jest',
  isNot: 'Nie jest',
  before: 'Przed',
  after: 'Po',
  dateIs: 'Data to',
  dateIsNot: 'Data nie to',
  dateBefore: 'Data przed',
  dateAfter: 'Data po',
  clear: 'Wyczyść',
  apply: 'Zastosuj',
  matchAll: 'Dopasuj wszystkie',
  matchAny: 'Dopasuj dowolne',
  addRule: 'Dodaj regułę',
  removeRule: 'Usuń regułę',
  accept: 'Tak',
  reject: 'Nie',
  choose: 'Wybierz',
  upload: 'Prześlij',
  cancel: 'Anuluj',
  completed: 'Zakończone',
  pending: 'Oczekujące',
  fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
  dayNames: ['niedziela', 'poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek', 'sobota'],
  dayNamesShort: ['nie', 'pon', 'wto', 'śro', 'czw', 'pią', 'sob'],
  dayNamesMin: ['Nd', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So'],
  monthNames: [
    'styczeń',
    'luty',
    'marzec',
    'kwiecień',
    'maj',
    'czerwiec',
    'lipiec',
    'sierpień',
    'wrzesień',
    'październik',
    'listopad',
    'grudzień',
  ],
  monthNamesShort: [
    'sty',
    'lut',
    'mar',
    'kwi',
    'maj',
    'cze',
    'lip',
    'sie',
    'wrz',
    'paź',
    'lis',
    'gru',
  ],
  chooseYear: 'Wybierz rok',
  chooseMonth: 'Wybierz miesiąc',
  chooseDate: 'Wybierz datę',
  prevDecade: 'Poprzednia dekada',
  nextDecade: 'Następna dekada',
  prevYear: 'Poprzedni rok',
  nextYear: 'Następny rok',
  prevMonth: 'Poprzedni miesiąc',
  nextMonth: 'Następny miesiąc',
  prevHour: 'Poprzednia godzina',
  nextHour: 'Następna godzina',
  prevMinute: 'Poprzednia minuta',
  nextMinute: 'Następna minuta',
  prevSecond: 'Poprzednia sekunda',
  nextSecond: 'Następna sekunda',
  am: 'AM',
  pm: 'PM',
  dateFormat: 'dd.mm.yy',
  firstDayOfWeek: 1,
  today: 'Dziś',
  weekHeader: 'Tydz.',
  weak: 'Słabe',
  medium: 'Średnie',
  strong: 'Silne',
  passwordPrompt: 'Wprowadź hasło',
  emptyMessage: 'Brak wyników',
  emptyFilterMessage: 'Brak wyników',
  searchMessage: 'Dostępnych {0} wyników',
  selectionMessage: 'Wybrano {0} pozycji',
  emptySelectionMessage: 'Brak wybranej pozycji',
  emptySearchMessage: 'Brak wyników wyszukiwania',
  fileChosenMessage: 'Wybrano plików: {0}',
  noFileChosenMessage: 'Nie wybrano pliku',
  aria: {
    trueLabel: 'Prawda',
    falseLabel: 'Fałsz',
    nullLabel: 'Nie wybrano',
    star: '1 gwiazdka',
    stars: '{star} gwiazdek',
    selectAll: 'Zaznacz wszystko',
    unselectAll: 'Odznacz wszystko',
    close: 'Zamknij',
    previous: 'Poprzedni',
    next: 'Następny',
    navigation: 'Nawigacja',
    scrollTop: 'Przewiń do góry',
    moveTop: 'Przenieś na górę',
    moveUp: 'Przenieś wyżej',
    moveDown: 'Przenieś niżej',
    moveBottom: 'Przenieś na dół',
    moveToTarget: 'Przenieś do wybranych',
    moveToSource: 'Przenieś do dostępnych',
    moveAllToTarget: 'Przenieś wszystko do wybranych',
    moveAllToSource: 'Przenieś wszystko do dostępnych',
    pageLabel: 'Strona {page}',
    firstPageLabel: 'Pierwsza strona',
    lastPageLabel: 'Ostatnia strona',
    nextPageLabel: 'Następna strona',
    prevPageLabel: 'Poprzednia strona',
    rowsPerPageLabel: 'Wierszy na stronę',
    previousPageLabel: 'Poprzednia strona',
    jumpToPageDropdownLabel: 'Przejdź do strony',
    jumpToPageInputLabel: 'Przejdź do strony',
    selectRow: 'Wiersz zaznaczony',
    unselectRow: 'Wiersz odznaczony',
    expandRow: 'Rozwiń wiersz',
    collapseRow: 'Zwiń wiersz',
    showFilterMenu: 'Pokaż menu filtrowania',
    hideFilterMenu: 'Ukryj menu filtrowania',
    filterOperator: 'Operator filtra',
    filterConstraint: 'Warunek filtra',
    editRow: 'Edytuj wiersz',
    saveEdit: 'Zapisz edycję',
    cancelEdit: 'Anuluj edycję',
    listView: 'Widok listy',
    gridView: 'Widok siatki',
    slide: 'Slajd',
    slideNumber: 'Slajd {slideNumber}',
    zoomImage: 'Powiększ obraz',
    zoomIn: 'Powiększ',
    zoomOut: 'Pomniejsz',
    rotateRight: 'Obróć w prawo',
    rotateLeft: 'Obróć w lewo',
    listLabel: 'Lista opcji',
    selectColor: 'Wybierz kolor',
    removeLabel: 'Usuń',
    browseFiles: 'Przeglądaj pliki',
    maximizeLabel: 'Maksymalizuj',
    minimizeLabel: 'Minimalizuj',
  },
};
