/** SQL literal helpers and the Liquibase formatted-SQL writer. */

export const HEADER = '-- GENERATED by apps/his_frontend/scripts/export-mocks, do not edit';

/** A fragment emitted verbatim (function calls, interval expressions, DEFAULT). */
export class Raw {
  constructor(readonly sql: string) {}
}

export const raw = (sql: string): Raw => new Raw(sql);
export const DEFAULT = raw('DEFAULT');

export type SqlValue = string | number | boolean | null | Raw;

export function literal(value: SqlValue | undefined, where: string): string {
  if (value === undefined) throw new Error(`undefined SQL value (${where})`);
  if (value === null) return 'NULL';
  if (value instanceof Raw) return value.sql;
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`non-finite number (${where})`);
    return String(value);
  }
  if (value.includes('${')) throw new Error(`Liquibase property placeholder in text (${where})`);
  return `'${value.replace(/'/g, "''")}'`;
}

export interface TableRows {
  table: string;
  columns: string[];
  rows: SqlValue[][];
}

/** Collects rows of one table; `add` takes an object keyed by column name and checks completeness. */
export class Table {
  readonly rows: SqlValue[][] = [];

  constructor(
    readonly name: string,
    readonly columns: string[],
  ) {}

  add(row: Record<string, SqlValue | undefined>): void {
    const extra = Object.keys(row).filter((k) => !this.columns.includes(k));
    if (extra.length) throw new Error(`${this.name}: unknown columns ${extra.join(', ')}`);
    this.rows.push(this.columns.map((c) => cell(row[c], `${this.name}.${c}`)));
  }

  get count(): number {
    return this.rows.length;
  }

  insert(): string {
    if (this.rows.length === 0) return '';
    const values = this.rows
      .map(
        (r, i) =>
          `    (${r.map((v, j) => literal(v, `${this.name}[${i}].${this.columns[j]}`)).join(', ')})`,
      )
      .join(',\n');
    return `INSERT INTO ${this.name} (${this.columns.join(', ')}) VALUES\n${values};`;
  }
}

function cell(value: SqlValue | undefined, where: string): SqlValue {
  if (value === undefined) throw new Error(`missing value for ${where}`);
  return value;
}

export interface Changeset {
  /** e.g. `001-ward` */
  id: string;
  statements: string[];
}

export interface SqlFile {
  /** Path relative to db/changelog, e.g. `mock/001-staff.sql`. */
  path: string;
  author: string;
  context: 'reference' | 'mock';
  changesets: Changeset[];
}

/** `--liquibase formatted sql` has to be the very first line, otherwise Liquibase treats it as plain SQL. */
export function renderFile(file: SqlFile): string {
  const out: string[] = ['--liquibase formatted sql', HEADER, ''];
  for (const cs of file.changesets) {
    out.push(`--changeset ${file.author}:${cs.id} context:${file.context}`);
    for (const st of cs.statements) {
      if (st) out.push(st);
    }
    out.push('');
  }
  return out.join('\n');
}
